# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/sda5/Projects/Prymatex/prymatex/resources/ui/configure/edit.ui'
#
# Created: Wed Dec 10 16:51:31 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Edit(object):
    def setupUi(self, Edit):
        Edit.setObjectName("Edit")
        Edit.resize(389, 376)
        self.verticalLayout = QtWidgets.QVBoxLayout(Edit)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Edit)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setContentsMargins(6, 6, 6, 6)
        self.formLayout.setSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.checkBoxAutoBrackets = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxAutoBrackets.setObjectName("checkBoxAutoBrackets")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBoxAutoBrackets)
        self.checkBoxRemoveTrailingSpaces = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxRemoveTrailingSpaces.setObjectName("checkBoxRemoveTrailingSpaces")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBoxRemoveTrailingSpaces)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(Edit)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(6, 6, 6, 6)
        self.formLayout_4.setSpacing(2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.radioButtonTabulators = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButtonTabulators.setObjectName("radioButtonTabulators")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButtonTabulators)
        self.radioButtonSpaces = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButtonSpaces.setObjectName("radioButtonSpaces")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButtonSpaces)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBoxIndentationWidth = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBoxIndentationWidth.setMinimum(2)
        self.spinBoxIndentationWidth.setMaximum(20)
        self.spinBoxIndentationWidth.setProperty("value", 4)
        self.spinBoxIndentationWidth.setObjectName("spinBoxIndentationWidth")
        self.horizontalLayout_3.addWidget(self.spinBoxIndentationWidth)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.checkBoxAdjustIndentationOnPaste = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBoxAdjustIndentationOnPaste.setObjectName("checkBoxAdjustIndentationOnPaste")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.checkBoxAdjustIndentationOnPaste)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(Edit)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setContentsMargins(6, 6, 6, 6)
        self.formLayout_2.setSpacing(2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.checkBoxSmartHomeSmartEnd = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxSmartHomeSmartEnd.setObjectName("checkBoxSmartHomeSmartEnd")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBoxSmartHomeSmartEnd)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Edit)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setContentsMargins(6, 6, 6, 6)
        self.formLayout_3.setSpacing(2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.checkBoxEnableAutoCompletion = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBoxEnableAutoCompletion.setObjectName("checkBoxEnableAutoCompletion")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBoxEnableAutoCompletion)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBoxWordLengthToComplete = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxWordLengthToComplete.setMinimum(3)
        self.spinBoxWordLengthToComplete.setMaximum(10)
        self.spinBoxWordLengthToComplete.setObjectName("spinBoxWordLengthToComplete")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxWordLengthToComplete)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem1 = QtWidgets.QSpacerItem(17, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Edit)
        QtCore.QMetaObject.connectSlotsByName(Edit)

    def retranslateUi(self, Edit):
        _translate = QtCore.QCoreApplication.translate
        Edit.setWindowTitle(_translate("Edit", "Edit"))
        self.groupBox_2.setTitle(_translate("Edit", "Misc"))
        self.checkBoxAutoBrackets.setText(_translate("Edit", "Auto brackets"))
        self.checkBoxRemoveTrailingSpaces.setText(_translate("Edit", "Remove trailing spaces while editing"))
        self.groupBox_5.setTitle(_translate("Edit", "Indentation"))
        self.radioButtonTabulators.setText(_translate("Edit", "Tabulators"))
        self.radioButtonSpaces.setText(_translate("Edit", "Spaces"))
        self.label_4.setText(_translate("Edit", "Indentation width:"))
        self.checkBoxAdjustIndentationOnPaste.setText(_translate("Edit", "Adjust indentation of code pasted from the clipboard"))
        self.groupBox_3.setTitle(_translate("Edit", "Text Cursor"))
        self.checkBoxSmartHomeSmartEnd.setText(_translate("Edit", "Smart home and smart end"))
        self.groupBox_4.setTitle(_translate("Edit", "Auto Completion"))
        self.checkBoxEnableAutoCompletion.setText(_translate("Edit", "Enable auto completion"))
        self.label.setText(_translate("Edit", "Minimal word length to complete:"))

