# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/sda5/Projects/Prymatex/prymatex/resources/ui/configure/theme.ui'
#
# Created: Tue Dec  9 16:01:56 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FontTheme(object):
    def setupUi(self, FontTheme):
        FontTheme.setObjectName("FontTheme")
        FontTheme.resize(605, 728)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FontTheme)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxFont_2 = QtWidgets.QGroupBox(FontTheme)
        self.groupBoxFont_2.setObjectName("groupBoxFont_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxFont_2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fontComboBoxName = QtWidgets.QFontComboBox(self.groupBoxFont_2)
        self.fontComboBoxName.setFontFilters(QtWidgets.QFontComboBox.MonospacedFonts)
        self.fontComboBoxName.setObjectName("fontComboBoxName")
        self.horizontalLayout_4.addWidget(self.fontComboBoxName)
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.groupBoxFont_2)
        self.spinBoxFontSize.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBoxFontSize.setMinimum(7)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.horizontalLayout_4.addWidget(self.spinBoxFontSize)
        self.checkBoxAntialias = QtWidgets.QCheckBox(self.groupBoxFont_2)
        self.checkBoxAntialias.setMaximumSize(QtCore.QSize(80, 16777215))
        self.checkBoxAntialias.setObjectName("checkBoxAntialias")
        self.horizontalLayout_4.addWidget(self.checkBoxAntialias)
        self.verticalLayout_2.addWidget(self.groupBoxFont_2)
        self.groupBoxTheme = QtWidgets.QGroupBox(FontTheme)
        self.groupBoxTheme.setObjectName("groupBoxTheme")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxTheme)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxThemes = QtWidgets.QComboBox(self.groupBoxTheme)
        self.comboBoxThemes.setObjectName("comboBoxThemes")
        self.verticalLayout.addWidget(self.comboBoxThemes)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonInvisibles = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonInvisibles.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonInvisibles.setText("")
        self.pushButtonInvisibles.setObjectName("pushButtonInvisibles")
        self.gridLayout.addWidget(self.pushButtonInvisibles, 0, 3, 1, 1)
        self.pushButtonSelection = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonSelection.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonSelection.setText("")
        self.pushButtonSelection.setObjectName("pushButtonSelection")
        self.gridLayout.addWidget(self.pushButtonSelection, 2, 1, 1, 1)
        self.pushButtonCaret = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonCaret.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonCaret.setText("")
        self.pushButtonCaret.setObjectName("pushButtonCaret")
        self.gridLayout.addWidget(self.pushButtonCaret, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        self.pushButtonBackground = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonBackground.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonBackground.setText("")
        self.pushButtonBackground.setObjectName("pushButtonBackground")
        self.gridLayout.addWidget(self.pushButtonBackground, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButtonForeground = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonForeground.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonForeground.setText("")
        self.pushButtonForeground.setObjectName("pushButtonForeground")
        self.gridLayout.addWidget(self.pushButtonForeground, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.pushButtonGutterBackground = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonGutterBackground.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonGutterBackground.setText("")
        self.pushButtonGutterBackground.setObjectName("pushButtonGutterBackground")
        self.gridLayout.addWidget(self.pushButtonGutterBackground, 3, 3, 1, 1)
        self.pushButtonLineHighlight = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonLineHighlight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonLineHighlight.setText("")
        self.pushButtonLineHighlight.setObjectName("pushButtonLineHighlight")
        self.gridLayout.addWidget(self.pushButtonLineHighlight, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.pushButtonGutterForeground = QtWidgets.QPushButton(self.groupBoxTheme)
        self.pushButtonGutterForeground.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButtonGutterForeground.setText("")
        self.pushButtonGutterForeground.setObjectName("pushButtonGutterForeground")
        self.gridLayout.addWidget(self.pushButtonGutterForeground, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tableViewStyles = QtWidgets.QTableView(self.groupBoxTheme)
        self.tableViewStyles.setShowGrid(False)
        self.tableViewStyles.setSortingEnabled(True)
        self.tableViewStyles.setObjectName("tableViewStyles")
        self.verticalLayout.addWidget(self.tableViewStyles)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonAdd = QtWidgets.QPushButton(self.groupBoxTheme)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButtonAdd.setIcon(icon)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_3.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(self.groupBoxTheme)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButtonRemove.setIcon(icon)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.horizontalLayout_3.addWidget(self.pushButtonRemove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.groupBoxTheme)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.comboBoxScope = QtWidgets.QComboBox(self.groupBoxTheme)
        self.comboBoxScope.setEditable(True)
        self.comboBoxScope.setObjectName("comboBoxScope")
        self.horizontalLayout_3.addWidget(self.comboBoxScope)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBoxTheme)

        self.retranslateUi(FontTheme)
        QtCore.QMetaObject.connectSlotsByName(FontTheme)

    def retranslateUi(self, FontTheme):
        _translate = QtCore.QCoreApplication.translate
        FontTheme.setWindowTitle(_translate("FontTheme", "Form"))
        self.groupBoxFont_2.setTitle(_translate("FontTheme", "Font"))
        self.checkBoxAntialias.setText(_translate("FontTheme", "Anti alias"))
        self.groupBoxTheme.setTitle(_translate("FontTheme", "Theme"))
        self.label_6.setText(_translate("FontTheme", "Invisibles:"))
        self.label_4.setText(_translate("FontTheme", "Background:"))
        self.label_10.setText(_translate("FontTheme", "Gutter background:"))
        self.label_5.setText(_translate("FontTheme", "Selection:"))
        self.label_3.setText(_translate("FontTheme", "Foreground:"))
        self.label_7.setText(_translate("FontTheme", "Caret:"))
        self.label_8.setText(_translate("FontTheme", "Line highlight:"))
        self.label_11.setText(_translate("FontTheme", "Gutter foreground:"))
        self.label_9.setText(_translate("FontTheme", "Scope selector:"))

