# generated by 'xml2py'
# flags '-c -d -l libonig.so -v -o lib/ctypes/onig_linux2.py ongdefs.xml'
from ctypes import *

_libraries = {}
_libraries['libonig.so'] = CDLL('libonig.so')
STRING = c_char_p


OnigUChar = c_ubyte
OnigCodePoint = c_ulong
OnigCtype = c_uint
OnigDistance = c_uint
OnigCaseFoldType = c_uint
OnigDefaultCaseFoldFlag = (OnigCaseFoldType).in_dll(_libraries['libonig.so'], 'OnigDefaultCaseFoldFlag')
# /usr/include/oniguruma.h 132
class OnigCaseFoldCodeItem(Structure):
    pass
OnigCaseFoldCodeItem._fields_ = [
    # /usr/include/oniguruma.h 132
    ('byte_len', c_int),
    ('code_len', c_int),
    ('code', OnigCodePoint * 3),
]
# /usr/include/oniguruma.h 141
class OnigMetaCharTableType(Structure):
    pass
OnigMetaCharTableType._fields_ = [
    # /usr/include/oniguruma.h 141
    ('esc', OnigCodePoint),
    ('anychar', OnigCodePoint),
    ('anytime', OnigCodePoint),
    ('zero_or_one_time', OnigCodePoint),
    ('one_or_more_time', OnigCodePoint),
    ('anychar_anytime', OnigCodePoint),
]
OnigApplyAllCaseFoldFunc = CFUNCTYPE(c_int, OnigCodePoint, POINTER(OnigCodePoint), c_int, c_void_p)
# /usr/include/oniguruma.h 145
class OnigEncodingTypeST(Structure):
    pass
OnigEncodingTypeST._fields_ = [
    # /usr/include/oniguruma.h 145
    ('mbc_enc_len', CFUNCTYPE(c_int, POINTER(OnigUChar))),
    ('name', STRING),
    ('max_enc_len', c_int),
    ('min_enc_len', c_int),
    ('is_mbc_newline', CFUNCTYPE(c_int, POINTER(OnigUChar), POINTER(OnigUChar))),
    ('mbc_to_code', CFUNCTYPE(OnigCodePoint, POINTER(OnigUChar), POINTER(OnigUChar))),
    ('code_to_mbclen', CFUNCTYPE(c_int, OnigCodePoint)),
    ('code_to_mbc', CFUNCTYPE(c_int, OnigCodePoint, POINTER(OnigUChar))),
    ('mbc_case_fold', CFUNCTYPE(c_int, OnigCaseFoldType, POINTER(POINTER(OnigUChar)), POINTER(OnigUChar), POINTER(OnigUChar))),
    ('apply_all_case_fold', CFUNCTYPE(c_int, OnigCaseFoldType, OnigApplyAllCaseFoldFunc, c_void_p)),
    ('get_case_fold_codes_by_str', CFUNCTYPE(c_int, OnigCaseFoldType, POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigCaseFoldCodeItem))),
    ('property_name_to_ctype', CFUNCTYPE(c_int, POINTER(OnigEncodingTypeST), POINTER(OnigUChar), POINTER(OnigUChar))),
    ('is_code_ctype', CFUNCTYPE(c_int, OnigCodePoint, OnigCtype)),
    ('get_ctype_code_range', CFUNCTYPE(c_int, OnigCtype, POINTER(OnigCodePoint), POINTER(POINTER(OnigCodePoint)))),
    ('left_adjust_char_head', CFUNCTYPE(POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigUChar))),
    ('is_allowed_reverse_match', CFUNCTYPE(c_int, POINTER(OnigUChar), POINTER(OnigUChar))),
]
OnigEncodingType = OnigEncodingTypeST
OnigEncoding = POINTER(OnigEncodingType)
OnigEncodingASCII = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingASCII')
OnigEncodingISO_8859_1 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_1')
OnigEncodingISO_8859_2 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_2')
OnigEncodingISO_8859_3 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_3')
OnigEncodingISO_8859_4 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_4')
OnigEncodingISO_8859_5 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_5')
OnigEncodingISO_8859_6 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_6')
OnigEncodingISO_8859_7 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_7')
OnigEncodingISO_8859_8 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_8')
OnigEncodingISO_8859_9 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_9')
OnigEncodingISO_8859_10 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_10')
OnigEncodingISO_8859_11 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_11')
OnigEncodingISO_8859_13 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_13')
OnigEncodingISO_8859_14 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_14')
OnigEncodingISO_8859_15 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_15')
OnigEncodingISO_8859_16 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingISO_8859_16')
OnigEncodingUTF8 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingUTF8')
OnigEncodingUTF16_BE = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingUTF16_BE')
OnigEncodingUTF16_LE = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingUTF16_LE')
OnigEncodingUTF32_BE = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingUTF32_BE')
OnigEncodingUTF32_LE = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingUTF32_LE')
OnigEncodingEUC_JP = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingEUC_JP')
OnigEncodingEUC_TW = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingEUC_TW')
OnigEncodingEUC_KR = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingEUC_KR')
OnigEncodingEUC_CN = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingEUC_CN')
OnigEncodingSJIS = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingSJIS')
OnigEncodingKOI8_R = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingKOI8_R')
OnigEncodingCP1251 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingCP1251')
OnigEncodingBIG5 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingBIG5')
OnigEncodingGB18030 = (OnigEncodingType).in_dll(_libraries['libonig.so'], 'OnigEncodingGB18030')
# /usr/include/oniguruma.h 329
onigenc_step_back = _libraries['libonig.so'].onigenc_step_back
onigenc_step_back.restype = POINTER(OnigUChar)
# onigenc_step_back(enc, start, s, n)
onigenc_step_back.argtypes = [OnigEncoding, POINTER(OnigUChar), POINTER(OnigUChar), c_int]
onigenc_step_back.__doc__ = \
"""OnigUChar * onigenc_step_back(OnigEncoding enc, unknown * start, unknown * s, int n)
/usr/include/oniguruma.h:329"""
# /usr/include/oniguruma.h 334
onigenc_init = _libraries['libonig.so'].onigenc_init
onigenc_init.restype = c_int
# onigenc_init()
onigenc_init.argtypes = []
onigenc_init.__doc__ = \
"""int onigenc_init()
/usr/include/oniguruma.h:334"""
# /usr/include/oniguruma.h 336
onigenc_set_default_encoding = _libraries['libonig.so'].onigenc_set_default_encoding
onigenc_set_default_encoding.restype = c_int
# onigenc_set_default_encoding(enc)
onigenc_set_default_encoding.argtypes = [OnigEncoding]
onigenc_set_default_encoding.__doc__ = \
"""int onigenc_set_default_encoding(OnigEncoding enc)
/usr/include/oniguruma.h:336"""
# /usr/include/oniguruma.h 338
onigenc_get_default_encoding = _libraries['libonig.so'].onigenc_get_default_encoding
onigenc_get_default_encoding.restype = OnigEncoding
# onigenc_get_default_encoding()
onigenc_get_default_encoding.argtypes = []
onigenc_get_default_encoding.__doc__ = \
"""OnigEncoding onigenc_get_default_encoding()
/usr/include/oniguruma.h:338"""
# /usr/include/oniguruma.h 340
onigenc_set_default_caseconv_table = _libraries['libonig.so'].onigenc_set_default_caseconv_table
onigenc_set_default_caseconv_table.restype = None
# onigenc_set_default_caseconv_table(table)
onigenc_set_default_caseconv_table.argtypes = [POINTER(OnigUChar)]
onigenc_set_default_caseconv_table.__doc__ = \
"""void onigenc_set_default_caseconv_table(unknown * table)
/usr/include/oniguruma.h:340"""
# /usr/include/oniguruma.h 342
onigenc_get_right_adjust_char_head_with_prev = _libraries['libonig.so'].onigenc_get_right_adjust_char_head_with_prev
onigenc_get_right_adjust_char_head_with_prev.restype = POINTER(OnigUChar)
# onigenc_get_right_adjust_char_head_with_prev(enc, start, s, prev)
onigenc_get_right_adjust_char_head_with_prev.argtypes = [OnigEncoding, POINTER(OnigUChar), POINTER(OnigUChar), POINTER(POINTER(OnigUChar))]
onigenc_get_right_adjust_char_head_with_prev.__doc__ = \
"""OnigUChar * onigenc_get_right_adjust_char_head_with_prev(OnigEncoding enc, unknown * start, unknown * s, unknown * * prev)
/usr/include/oniguruma.h:342"""
# /usr/include/oniguruma.h 344
onigenc_get_prev_char_head = _libraries['libonig.so'].onigenc_get_prev_char_head
onigenc_get_prev_char_head.restype = POINTER(OnigUChar)
# onigenc_get_prev_char_head(enc, start, s)
onigenc_get_prev_char_head.argtypes = [OnigEncoding, POINTER(OnigUChar), POINTER(OnigUChar)]
onigenc_get_prev_char_head.__doc__ = \
"""OnigUChar * onigenc_get_prev_char_head(OnigEncoding enc, unknown * start, unknown * s)
/usr/include/oniguruma.h:344"""
# /usr/include/oniguruma.h 346
onigenc_get_left_adjust_char_head = _libraries['libonig.so'].onigenc_get_left_adjust_char_head
onigenc_get_left_adjust_char_head.restype = POINTER(OnigUChar)
# onigenc_get_left_adjust_char_head(enc, start, s)
onigenc_get_left_adjust_char_head.argtypes = [OnigEncoding, POINTER(OnigUChar), POINTER(OnigUChar)]
onigenc_get_left_adjust_char_head.__doc__ = \
"""OnigUChar * onigenc_get_left_adjust_char_head(OnigEncoding enc, unknown * start, unknown * s)
/usr/include/oniguruma.h:346"""
# /usr/include/oniguruma.h 348
onigenc_get_right_adjust_char_head = _libraries['libonig.so'].onigenc_get_right_adjust_char_head
onigenc_get_right_adjust_char_head.restype = POINTER(OnigUChar)
# onigenc_get_right_adjust_char_head(enc, start, s)
onigenc_get_right_adjust_char_head.argtypes = [OnigEncoding, POINTER(OnigUChar), POINTER(OnigUChar)]
onigenc_get_right_adjust_char_head.__doc__ = \
"""OnigUChar * onigenc_get_right_adjust_char_head(OnigEncoding enc, unknown * start, unknown * s)
/usr/include/oniguruma.h:348"""
# /usr/include/oniguruma.h 350
onigenc_strlen = _libraries['libonig.so'].onigenc_strlen
onigenc_strlen.restype = c_int
# onigenc_strlen(enc, p, end)
onigenc_strlen.argtypes = [OnigEncoding, POINTER(OnigUChar), POINTER(OnigUChar)]
onigenc_strlen.__doc__ = \
"""int onigenc_strlen(OnigEncoding enc, unknown * p, unknown * end)
/usr/include/oniguruma.h:350"""
# /usr/include/oniguruma.h 352
onigenc_strlen_null = _libraries['libonig.so'].onigenc_strlen_null
onigenc_strlen_null.restype = c_int
# onigenc_strlen_null(enc, p)
onigenc_strlen_null.argtypes = [OnigEncoding, POINTER(OnigUChar)]
onigenc_strlen_null.__doc__ = \
"""int onigenc_strlen_null(OnigEncoding enc, unknown * p)
/usr/include/oniguruma.h:352"""
# /usr/include/oniguruma.h 354
onigenc_str_bytelen_null = _libraries['libonig.so'].onigenc_str_bytelen_null
onigenc_str_bytelen_null.restype = c_int
# onigenc_str_bytelen_null(enc, p)
onigenc_str_bytelen_null.argtypes = [OnigEncoding, POINTER(OnigUChar)]
onigenc_str_bytelen_null.__doc__ = \
"""int onigenc_str_bytelen_null(OnigEncoding enc, unknown * p)
/usr/include/oniguruma.h:354"""
OnigOptionType = c_uint
# /usr/include/oniguruma.h 400
class OnigSyntaxType(Structure):
    pass
OnigSyntaxType._fields_ = [
    # /usr/include/oniguruma.h 400
    ('op', c_uint),
    ('op2', c_uint),
    ('behavior', c_uint),
    ('options', OnigOptionType),
    ('meta_char_table', OnigMetaCharTableType),
]
OnigSyntaxASIS = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxASIS')
OnigSyntaxPosixBasic = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxPosixBasic')
OnigSyntaxPosixExtended = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxPosixExtended')
OnigSyntaxEmacs = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxEmacs')
OnigSyntaxGrep = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxGrep')
OnigSyntaxGnuRegex = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxGnuRegex')
OnigSyntaxJava = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxJava')
OnigSyntaxPerl = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxPerl')
OnigSyntaxPerl_NG = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxPerl_NG')
OnigSyntaxRuby = (OnigSyntaxType).in_dll(_libraries['libonig.so'], 'OnigSyntaxRuby')
OnigDefaultSyntax = (POINTER(OnigSyntaxType)).in_dll(_libraries['libonig.so'], 'OnigDefaultSyntax')
# /usr/include/oniguruma.h 595
class OnigCaptureTreeNodeStruct(Structure):
    pass
OnigCaptureTreeNodeStruct._fields_ = [
    # /usr/include/oniguruma.h 595
    ('group', c_int),
    ('beg', c_int),
    ('end', c_int),
    ('allocated', c_int),
    ('num_childs', c_int),
    ('childs', POINTER(POINTER(OnigCaptureTreeNodeStruct))),
]
OnigCaptureTreeNode = OnigCaptureTreeNodeStruct
# /usr/include/oniguruma.h 605
class re_registers(Structure):
    pass
re_registers._fields_ = [
    # /usr/include/oniguruma.h 605
    ('allocated', c_int),
    ('num_regs', c_int),
    ('beg', POINTER(c_int)),
    ('end', POINTER(c_int)),
    ('history_root', POINTER(OnigCaptureTreeNode)),
]
OnigRegion = re_registers
# /usr/include/oniguruma.h 629
class OnigErrorInfo(Structure):
    pass
OnigErrorInfo._fields_ = [
    # /usr/include/oniguruma.h 629
    ('enc', OnigEncoding),
    ('par', POINTER(OnigUChar)),
    ('par_end', POINTER(OnigUChar)),
]
# /usr/include/oniguruma.h 634
class OnigRepeatRange(Structure):
    pass
OnigRepeatRange._fields_ = [
    # /usr/include/oniguruma.h 634
    ('lower', c_int),
    ('upper', c_int),
]
OnigWarnFunc = CFUNCTYPE(None, STRING)
# /usr/include/oniguruma.h 637
onig_null_warn = _libraries['libonig.so'].onig_null_warn
onig_null_warn.restype = None
# onig_null_warn(s)
onig_null_warn.argtypes = [STRING]
onig_null_warn.__doc__ = \
"""void onig_null_warn(unknown * s)
/usr/include/oniguruma.h:637"""
# /usr/include/oniguruma.h 651
class re_pattern_buffer(Structure):
    pass
re_pattern_buffer._fields_ = [
    # /usr/include/oniguruma.h 651
    ('p', POINTER(c_ubyte)),
    ('used', c_uint),
    ('alloc', c_uint),
    ('state', c_int),
    ('num_mem', c_int),
    ('num_repeat', c_int),
    ('num_null_check', c_int),
    ('num_comb_exp_check', c_int),
    ('num_call', c_int),
    ('capture_history', c_uint),
    ('bt_mem_start', c_uint),
    ('bt_mem_end', c_uint),
    ('stack_pop_level', c_int),
    ('repeat_range_alloc', c_int),
    ('repeat_range', POINTER(OnigRepeatRange)),
    ('enc', OnigEncoding),
    ('options', OnigOptionType),
    ('syntax', POINTER(OnigSyntaxType)),
    ('case_fold_flag', OnigCaseFoldType),
    ('name_table', c_void_p),
    ('optimize', c_int),
    ('threshold_len', c_int),
    ('anchor', c_int),
    ('anchor_dmin', OnigDistance),
    ('anchor_dmax', OnigDistance),
    ('sub_anchor', c_int),
    ('exact', POINTER(c_ubyte)),
    ('exact_end', POINTER(c_ubyte)),
    ('map', c_ubyte * 256),
    ('int_map', POINTER(c_int)),
    ('int_map_backward', POINTER(c_int)),
    ('dmin', OnigDistance),
    ('dmax', OnigDistance),
    ('chain', POINTER(re_pattern_buffer)),
]
OnigRegexType = re_pattern_buffer
OnigRegex = POINTER(OnigRegexType)
regex_t = OnigRegexType
# /usr/include/oniguruma.h 709
class OnigCompileInfo(Structure):
    pass
OnigCompileInfo._fields_ = [
    # /usr/include/oniguruma.h 709
    ('num_of_elements', c_int),
    ('pattern_enc', OnigEncoding),
    ('target_enc', OnigEncoding),
    ('syntax', POINTER(OnigSyntaxType)),
    ('option', OnigOptionType),
    ('case_fold_flag', OnigCaseFoldType),
]
# /usr/include/oniguruma.h 713
onig_init = _libraries['libonig.so'].onig_init
onig_init.restype = c_int
# onig_init()
onig_init.argtypes = []
onig_init.__doc__ = \
"""int onig_init()
/usr/include/oniguruma.h:713"""
# /usr/include/oniguruma.h 715
onig_error_code_to_str = _libraries['libonig.so'].onig_error_code_to_str
onig_error_code_to_str.restype = c_int
# onig_error_code_to_str(s, err_code)
onig_error_code_to_str.argtypes = [POINTER(OnigUChar), c_int]
onig_error_code_to_str.__doc__ = \
"""int onig_error_code_to_str(OnigUChar * s, int err_code)
/usr/include/oniguruma.h:715"""
# /usr/include/oniguruma.h 717
onig_set_warn_func = _libraries['libonig.so'].onig_set_warn_func
onig_set_warn_func.restype = None
# onig_set_warn_func(f)
onig_set_warn_func.argtypes = [OnigWarnFunc]
onig_set_warn_func.__doc__ = \
"""void onig_set_warn_func(OnigWarnFunc f)
/usr/include/oniguruma.h:717"""
# /usr/include/oniguruma.h 719
onig_set_verb_warn_func = _libraries['libonig.so'].onig_set_verb_warn_func
onig_set_verb_warn_func.restype = None
# onig_set_verb_warn_func(f)
onig_set_verb_warn_func.argtypes = [OnigWarnFunc]
onig_set_verb_warn_func.__doc__ = \
"""void onig_set_verb_warn_func(OnigWarnFunc f)
/usr/include/oniguruma.h:719"""
# /usr/include/oniguruma.h 721
onig_new = _libraries['libonig.so'].onig_new
onig_new.restype = c_int
# onig_new(p1, pattern, pattern_end, option, enc, syntax, einfo)
onig_new.argtypes = [POINTER(OnigRegex), POINTER(OnigUChar), POINTER(OnigUChar), OnigOptionType, OnigEncoding, POINTER(OnigSyntaxType), POINTER(OnigErrorInfo)]
onig_new.__doc__ = \
"""int onig_new(OnigRegex * p1, unknown * pattern, unknown * pattern_end, OnigOptionType option, OnigEncoding enc, OnigSyntaxType * syntax, OnigErrorInfo * einfo)
/usr/include/oniguruma.h:721"""
# /usr/include/oniguruma.h 723
onig_new_deluxe = _libraries['libonig.so'].onig_new_deluxe
onig_new_deluxe.restype = c_int
# onig_new_deluxe(reg, pattern, pattern_end, ci, einfo)
onig_new_deluxe.argtypes = [POINTER(OnigRegex), POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigCompileInfo), POINTER(OnigErrorInfo)]
onig_new_deluxe.__doc__ = \
"""int onig_new_deluxe(OnigRegex * reg, unknown * pattern, unknown * pattern_end, OnigCompileInfo * ci, OnigErrorInfo * einfo)
/usr/include/oniguruma.h:723"""
# /usr/include/oniguruma.h 725
onig_free = _libraries['libonig.so'].onig_free
onig_free.restype = None
# onig_free(p1)
onig_free.argtypes = [OnigRegex]
onig_free.__doc__ = \
"""void onig_free(OnigRegex p1)
/usr/include/oniguruma.h:725"""
# /usr/include/oniguruma.h 731
onig_search = _libraries['libonig.so'].onig_search
onig_search.restype = c_int
# onig_search(p1, str, end, start, range, region, option)
onig_search.argtypes = [OnigRegex, POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigRegion), OnigOptionType]
onig_search.__doc__ = \
"""int onig_search(OnigRegex p1, unknown * str, unknown * end, unknown * start, unknown * range, OnigRegion * region, OnigOptionType option)
/usr/include/oniguruma.h:731"""
# /usr/include/oniguruma.h 733
onig_match = _libraries['libonig.so'].onig_match
onig_match.restype = c_int
# onig_match(p1, str, end, at, region, option)
onig_match.argtypes = [OnigRegex, POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigRegion), OnigOptionType]
onig_match.__doc__ = \
"""int onig_match(OnigRegex p1, unknown * str, unknown * end, unknown * at, OnigRegion * region, OnigOptionType option)
/usr/include/oniguruma.h:733"""
# /usr/include/oniguruma.h 735
onig_region_new = _libraries['libonig.so'].onig_region_new
onig_region_new.restype = POINTER(OnigRegion)
# onig_region_new()
onig_region_new.argtypes = []
onig_region_new.__doc__ = \
"""OnigRegion * onig_region_new()
/usr/include/oniguruma.h:735"""
# /usr/include/oniguruma.h 737
onig_region_init = _libraries['libonig.so'].onig_region_init
onig_region_init.restype = None
# onig_region_init(region)
onig_region_init.argtypes = [POINTER(OnigRegion)]
onig_region_init.__doc__ = \
"""void onig_region_init(OnigRegion * region)
/usr/include/oniguruma.h:737"""
# /usr/include/oniguruma.h 739
onig_region_free = _libraries['libonig.so'].onig_region_free
onig_region_free.restype = None
# onig_region_free(region, free_self)
onig_region_free.argtypes = [POINTER(OnigRegion), c_int]
onig_region_free.__doc__ = \
"""void onig_region_free(OnigRegion * region, int free_self)
/usr/include/oniguruma.h:739"""
# /usr/include/oniguruma.h 741
onig_region_copy = _libraries['libonig.so'].onig_region_copy
onig_region_copy.restype = None
# onig_region_copy(to, from)
onig_region_copy.argtypes = [POINTER(OnigRegion), POINTER(OnigRegion)]
onig_region_copy.__doc__ = \
"""void onig_region_copy(OnigRegion * to, OnigRegion * from)
/usr/include/oniguruma.h:741"""
# /usr/include/oniguruma.h 743
onig_region_clear = _libraries['libonig.so'].onig_region_clear
onig_region_clear.restype = None
# onig_region_clear(region)
onig_region_clear.argtypes = [POINTER(OnigRegion)]
onig_region_clear.__doc__ = \
"""void onig_region_clear(OnigRegion * region)
/usr/include/oniguruma.h:743"""
# /usr/include/oniguruma.h 745
onig_region_resize = _libraries['libonig.so'].onig_region_resize
onig_region_resize.restype = c_int
# onig_region_resize(region, n)
onig_region_resize.argtypes = [POINTER(OnigRegion), c_int]
onig_region_resize.__doc__ = \
"""int onig_region_resize(OnigRegion * region, int n)
/usr/include/oniguruma.h:745"""
# /usr/include/oniguruma.h 747
onig_region_set = _libraries['libonig.so'].onig_region_set
onig_region_set.restype = c_int
# onig_region_set(region, at, beg, end)
onig_region_set.argtypes = [POINTER(OnigRegion), c_int, c_int, c_int]
onig_region_set.__doc__ = \
"""int onig_region_set(OnigRegion * region, int at, int beg, int end)
/usr/include/oniguruma.h:747"""
# /usr/include/oniguruma.h 749
onig_name_to_group_numbers = _libraries['libonig.so'].onig_name_to_group_numbers
onig_name_to_group_numbers.restype = c_int
# onig_name_to_group_numbers(reg, name, name_end, nums)
onig_name_to_group_numbers.argtypes = [OnigRegex, POINTER(OnigUChar), POINTER(OnigUChar), POINTER(POINTER(c_int))]
onig_name_to_group_numbers.__doc__ = \
"""int onig_name_to_group_numbers(OnigRegex reg, unknown * name, unknown * name_end, int * * nums)
/usr/include/oniguruma.h:749"""
# /usr/include/oniguruma.h 751
onig_name_to_backref_number = _libraries['libonig.so'].onig_name_to_backref_number
onig_name_to_backref_number.restype = c_int
# onig_name_to_backref_number(reg, name, name_end, region)
onig_name_to_backref_number.argtypes = [OnigRegex, POINTER(OnigUChar), POINTER(OnigUChar), POINTER(OnigRegion)]
onig_name_to_backref_number.__doc__ = \
"""int onig_name_to_backref_number(OnigRegex reg, unknown * name, unknown * name_end, OnigRegion * region)
/usr/include/oniguruma.h:751"""
# /usr/include/oniguruma.h 753
onig_foreach_name = _libraries['libonig.so'].onig_foreach_name
onig_foreach_name.restype = c_int
# onig_foreach_name(reg, func, arg)
onig_foreach_name.argtypes = [OnigRegex, CFUNCTYPE(c_int, POINTER(OnigUChar), POINTER(OnigUChar), c_int, POINTER(c_int), OnigRegex, c_void_p), c_void_p]
onig_foreach_name.__doc__ = \
"""int onig_foreach_name(OnigRegex reg, unknown * func, void * arg)
/usr/include/oniguruma.h:753"""
# /usr/include/oniguruma.h 755
onig_number_of_names = _libraries['libonig.so'].onig_number_of_names
onig_number_of_names.restype = c_int
# onig_number_of_names(reg)
onig_number_of_names.argtypes = [OnigRegex]
onig_number_of_names.__doc__ = \
"""int onig_number_of_names(OnigRegex reg)
/usr/include/oniguruma.h:755"""
# /usr/include/oniguruma.h 757
onig_number_of_captures = _libraries['libonig.so'].onig_number_of_captures
onig_number_of_captures.restype = c_int
# onig_number_of_captures(reg)
onig_number_of_captures.argtypes = [OnigRegex]
onig_number_of_captures.__doc__ = \
"""int onig_number_of_captures(OnigRegex reg)
/usr/include/oniguruma.h:757"""
# /usr/include/oniguruma.h 759
onig_number_of_capture_histories = _libraries['libonig.so'].onig_number_of_capture_histories
onig_number_of_capture_histories.restype = c_int
# onig_number_of_capture_histories(reg)
onig_number_of_capture_histories.argtypes = [OnigRegex]
onig_number_of_capture_histories.__doc__ = \
"""int onig_number_of_capture_histories(OnigRegex reg)
/usr/include/oniguruma.h:759"""
# /usr/include/oniguruma.h 761
onig_get_capture_tree = _libraries['libonig.so'].onig_get_capture_tree
onig_get_capture_tree.restype = POINTER(OnigCaptureTreeNode)
# onig_get_capture_tree(region)
onig_get_capture_tree.argtypes = [POINTER(OnigRegion)]
onig_get_capture_tree.__doc__ = \
"""OnigCaptureTreeNode * onig_get_capture_tree(OnigRegion * region)
/usr/include/oniguruma.h:761"""
# /usr/include/oniguruma.h 763
onig_capture_tree_traverse = _libraries['libonig.so'].onig_capture_tree_traverse
onig_capture_tree_traverse.restype = c_int
# onig_capture_tree_traverse(region, at, callback_func, arg)
onig_capture_tree_traverse.argtypes = [POINTER(OnigRegion), c_int, CFUNCTYPE(c_int, c_int, c_int, c_int, c_int, c_int, c_void_p), c_void_p]
onig_capture_tree_traverse.__doc__ = \
"""int onig_capture_tree_traverse(OnigRegion * region, int at, unknown * callback_func, void * arg)
/usr/include/oniguruma.h:763"""
# /usr/include/oniguruma.h 765
onig_noname_group_capture_is_active = _libraries['libonig.so'].onig_noname_group_capture_is_active
onig_noname_group_capture_is_active.restype = c_int
# onig_noname_group_capture_is_active(reg)
onig_noname_group_capture_is_active.argtypes = [OnigRegex]
onig_noname_group_capture_is_active.__doc__ = \
"""int onig_noname_group_capture_is_active(OnigRegex reg)
/usr/include/oniguruma.h:765"""
# /usr/include/oniguruma.h 767
onig_get_encoding = _libraries['libonig.so'].onig_get_encoding
onig_get_encoding.restype = OnigEncoding
# onig_get_encoding(reg)
onig_get_encoding.argtypes = [OnigRegex]
onig_get_encoding.__doc__ = \
"""OnigEncoding onig_get_encoding(OnigRegex reg)
/usr/include/oniguruma.h:767"""
# /usr/include/oniguruma.h 769
onig_get_options = _libraries['libonig.so'].onig_get_options
onig_get_options.restype = OnigOptionType
# onig_get_options(reg)
onig_get_options.argtypes = [OnigRegex]
onig_get_options.__doc__ = \
"""OnigOptionType onig_get_options(OnigRegex reg)
/usr/include/oniguruma.h:769"""
# /usr/include/oniguruma.h 771
onig_get_case_fold_flag = _libraries['libonig.so'].onig_get_case_fold_flag
onig_get_case_fold_flag.restype = OnigCaseFoldType
# onig_get_case_fold_flag(reg)
onig_get_case_fold_flag.argtypes = [OnigRegex]
onig_get_case_fold_flag.__doc__ = \
"""OnigCaseFoldType onig_get_case_fold_flag(OnigRegex reg)
/usr/include/oniguruma.h:771"""
# /usr/include/oniguruma.h 773
onig_get_syntax = _libraries['libonig.so'].onig_get_syntax
onig_get_syntax.restype = POINTER(OnigSyntaxType)
# onig_get_syntax(reg)
onig_get_syntax.argtypes = [OnigRegex]
onig_get_syntax.__doc__ = \
"""OnigSyntaxType * onig_get_syntax(OnigRegex reg)
/usr/include/oniguruma.h:773"""
# /usr/include/oniguruma.h 775
onig_set_default_syntax = _libraries['libonig.so'].onig_set_default_syntax
onig_set_default_syntax.restype = c_int
# onig_set_default_syntax(syntax)
onig_set_default_syntax.argtypes = [POINTER(OnigSyntaxType)]
onig_set_default_syntax.__doc__ = \
"""int onig_set_default_syntax(OnigSyntaxType * syntax)
/usr/include/oniguruma.h:775"""
# /usr/include/oniguruma.h 777
onig_copy_syntax = _libraries['libonig.so'].onig_copy_syntax
onig_copy_syntax.restype = None
# onig_copy_syntax(to, from)
onig_copy_syntax.argtypes = [POINTER(OnigSyntaxType), POINTER(OnigSyntaxType)]
onig_copy_syntax.__doc__ = \
"""void onig_copy_syntax(OnigSyntaxType * to, OnigSyntaxType * from)
/usr/include/oniguruma.h:777"""
# /usr/include/oniguruma.h 779
onig_get_syntax_op = _libraries['libonig.so'].onig_get_syntax_op
onig_get_syntax_op.restype = c_uint
# onig_get_syntax_op(syntax)
onig_get_syntax_op.argtypes = [POINTER(OnigSyntaxType)]
onig_get_syntax_op.__doc__ = \
"""unsigned int onig_get_syntax_op(OnigSyntaxType * syntax)
/usr/include/oniguruma.h:779"""
# /usr/include/oniguruma.h 781
onig_get_syntax_op2 = _libraries['libonig.so'].onig_get_syntax_op2
onig_get_syntax_op2.restype = c_uint
# onig_get_syntax_op2(syntax)
onig_get_syntax_op2.argtypes = [POINTER(OnigSyntaxType)]
onig_get_syntax_op2.__doc__ = \
"""unsigned int onig_get_syntax_op2(OnigSyntaxType * syntax)
/usr/include/oniguruma.h:781"""
# /usr/include/oniguruma.h 783
onig_get_syntax_behavior = _libraries['libonig.so'].onig_get_syntax_behavior
onig_get_syntax_behavior.restype = c_uint
# onig_get_syntax_behavior(syntax)
onig_get_syntax_behavior.argtypes = [POINTER(OnigSyntaxType)]
onig_get_syntax_behavior.__doc__ = \
"""unsigned int onig_get_syntax_behavior(OnigSyntaxType * syntax)
/usr/include/oniguruma.h:783"""
# /usr/include/oniguruma.h 785
onig_get_syntax_options = _libraries['libonig.so'].onig_get_syntax_options
onig_get_syntax_options.restype = OnigOptionType
# onig_get_syntax_options(syntax)
onig_get_syntax_options.argtypes = [POINTER(OnigSyntaxType)]
onig_get_syntax_options.__doc__ = \
"""OnigOptionType onig_get_syntax_options(OnigSyntaxType * syntax)
/usr/include/oniguruma.h:785"""
# /usr/include/oniguruma.h 787
onig_set_syntax_op = _libraries['libonig.so'].onig_set_syntax_op
onig_set_syntax_op.restype = None
# onig_set_syntax_op(syntax, op)
onig_set_syntax_op.argtypes = [POINTER(OnigSyntaxType), c_uint]
onig_set_syntax_op.__doc__ = \
"""void onig_set_syntax_op(OnigSyntaxType * syntax, unsigned int op)
/usr/include/oniguruma.h:787"""
# /usr/include/oniguruma.h 789
onig_set_syntax_op2 = _libraries['libonig.so'].onig_set_syntax_op2
onig_set_syntax_op2.restype = None
# onig_set_syntax_op2(syntax, op2)
onig_set_syntax_op2.argtypes = [POINTER(OnigSyntaxType), c_uint]
onig_set_syntax_op2.__doc__ = \
"""void onig_set_syntax_op2(OnigSyntaxType * syntax, unsigned int op2)
/usr/include/oniguruma.h:789"""
# /usr/include/oniguruma.h 791
onig_set_syntax_behavior = _libraries['libonig.so'].onig_set_syntax_behavior
onig_set_syntax_behavior.restype = None
# onig_set_syntax_behavior(syntax, behavior)
onig_set_syntax_behavior.argtypes = [POINTER(OnigSyntaxType), c_uint]
onig_set_syntax_behavior.__doc__ = \
"""void onig_set_syntax_behavior(OnigSyntaxType * syntax, unsigned int behavior)
/usr/include/oniguruma.h:791"""
# /usr/include/oniguruma.h 793
onig_set_syntax_options = _libraries['libonig.so'].onig_set_syntax_options
onig_set_syntax_options.restype = None
# onig_set_syntax_options(syntax, options)
onig_set_syntax_options.argtypes = [POINTER(OnigSyntaxType), OnigOptionType]
onig_set_syntax_options.__doc__ = \
"""void onig_set_syntax_options(OnigSyntaxType * syntax, OnigOptionType options)
/usr/include/oniguruma.h:793"""
# /usr/include/oniguruma.h 795
onig_set_meta_char = _libraries['libonig.so'].onig_set_meta_char
onig_set_meta_char.restype = c_int
# onig_set_meta_char(syntax, what, code)
onig_set_meta_char.argtypes = [POINTER(OnigSyntaxType), c_uint, OnigCodePoint]
onig_set_meta_char.__doc__ = \
"""int onig_set_meta_char(OnigSyntaxType * syntax, unsigned int what, OnigCodePoint code)
/usr/include/oniguruma.h:795"""
# /usr/include/oniguruma.h 797
onig_copy_encoding = _libraries['libonig.so'].onig_copy_encoding
onig_copy_encoding.restype = None
# onig_copy_encoding(to, from)
onig_copy_encoding.argtypes = [OnigEncoding, OnigEncoding]
onig_copy_encoding.__doc__ = \
"""void onig_copy_encoding(OnigEncoding to, OnigEncoding from)
/usr/include/oniguruma.h:797"""
# /usr/include/oniguruma.h 799
onig_get_default_case_fold_flag = _libraries['libonig.so'].onig_get_default_case_fold_flag
onig_get_default_case_fold_flag.restype = OnigCaseFoldType
# onig_get_default_case_fold_flag()
onig_get_default_case_fold_flag.argtypes = []
onig_get_default_case_fold_flag.__doc__ = \
"""OnigCaseFoldType onig_get_default_case_fold_flag()
/usr/include/oniguruma.h:799"""
# /usr/include/oniguruma.h 801
onig_set_default_case_fold_flag = _libraries['libonig.so'].onig_set_default_case_fold_flag
onig_set_default_case_fold_flag.restype = c_int
# onig_set_default_case_fold_flag(case_fold_flag)
onig_set_default_case_fold_flag.argtypes = [OnigCaseFoldType]
onig_set_default_case_fold_flag.__doc__ = \
"""int onig_set_default_case_fold_flag(OnigCaseFoldType case_fold_flag)
/usr/include/oniguruma.h:801"""
# /usr/include/oniguruma.h 803
onig_get_match_stack_limit_size = _libraries['libonig.so'].onig_get_match_stack_limit_size
onig_get_match_stack_limit_size.restype = c_uint
# onig_get_match_stack_limit_size()
onig_get_match_stack_limit_size.argtypes = []
onig_get_match_stack_limit_size.__doc__ = \
"""unsigned int onig_get_match_stack_limit_size()
/usr/include/oniguruma.h:803"""
# /usr/include/oniguruma.h 805
onig_set_match_stack_limit_size = _libraries['libonig.so'].onig_set_match_stack_limit_size
onig_set_match_stack_limit_size.restype = c_int
# onig_set_match_stack_limit_size(size)
onig_set_match_stack_limit_size.argtypes = [c_uint]
onig_set_match_stack_limit_size.__doc__ = \
"""int onig_set_match_stack_limit_size(unsigned int size)
/usr/include/oniguruma.h:805"""
# /usr/include/oniguruma.h 807
onig_end = _libraries['libonig.so'].onig_end
onig_end.restype = c_int
# onig_end()
onig_end.argtypes = []
onig_end.__doc__ = \
"""int onig_end()
/usr/include/oniguruma.h:807"""
# /usr/include/oniguruma.h 809
onig_version = _libraries['libonig.so'].onig_version
onig_version.restype = STRING
# onig_version()
onig_version.argtypes = []
onig_version.__doc__ = \
"""unknown * onig_version()
/usr/include/oniguruma.h:809"""
# /usr/include/oniguruma.h 811
onig_copyright = _libraries['libonig.so'].onig_copyright
onig_copyright.restype = STRING
# onig_copyright()
onig_copyright.argtypes = []
onig_copyright.__doc__ = \
"""unknown * onig_copyright()
/usr/include/oniguruma.h:811"""
__all__ = ['OnigEncodingISO_8859_3', 'OnigEncodingISO_8859_2',
           'OnigEncodingISO_8859_1', 'onig_region_init',
           'OnigEncodingISO_8859_7', 'OnigEncodingISO_8859_6',
           'OnigEncodingISO_8859_5', 'OnigEncodingTypeST',
           'OnigEncodingISO_8859_9', 'OnigEncodingISO_8859_8',
           'onig_get_syntax', 'OnigCompileInfo', 'onig_copy_encoding',
           'onig_set_default_syntax', 'OnigEncodingGB18030',
           'OnigSyntaxJava', 'OnigEncodingISO_8859_4',
           'onig_number_of_names', 'OnigEncodingCP1251',
           'onig_number_of_capture_histories',
           'OnigDefaultCaseFoldFlag',
           'onig_set_match_stack_limit_size', 'onig_version',
           'OnigMetaCharTableType', 'onig_get_syntax_op',
           'onigenc_get_right_adjust_char_head_with_prev',
           'onig_get_case_fold_flag', 'onig_error_code_to_str',
           'onig_set_syntax_options',
           'onig_set_default_case_fold_flag', 'onig_new_deluxe',
           'onig_region_set', 'OnigEncodingEUC_JP',
           'OnigCaptureTreeNode', 'OnigSyntaxRuby', 'regex_t',
           'OnigRegexType', 'onigenc_set_default_encoding',
           'onig_get_syntax_behavior', 're_registers', 'OnigWarnFunc',
           'onig_name_to_group_numbers', 'onig_search',
           'onigenc_str_bytelen_null',
           'onigenc_get_left_adjust_char_head', 'OnigEncodingKOI8_R',
           'OnigSyntaxASIS', 'onig_set_syntax_op2',
           'onig_get_encoding', 'onig_foreach_name',
           'onig_get_capture_tree', 'onig_capture_tree_traverse',
           'OnigEncodingEUC_TW', 'onig_set_syntax_op',
           'onigenc_step_back', 'OnigDistance', 'OnigEncodingBIG5',
           'onig_set_warn_func', 'OnigCtype', 'OnigEncodingSJIS',
           'OnigEncodingISO_8859_13', 'OnigEncodingISO_8859_11',
           'OnigEncodingISO_8859_10', 'OnigEncodingISO_8859_16',
           'OnigEncodingISO_8859_15', 'OnigEncodingISO_8859_14',
           'onig_get_syntax_options', 'onig_number_of_captures',
           'OnigEncodingUTF16_BE', 'OnigEncodingType',
           'OnigSyntaxGnuRegex', 'onig_region_free', 'onig_new',
           'OnigCaseFoldType', 'OnigRegion', 'onig_region_copy',
           'OnigSyntaxPosixBasic', 'OnigCaseFoldCodeItem',
           'OnigApplyAllCaseFoldFunc', 'onig_set_meta_char',
           'OnigSyntaxPerl_NG', 'OnigSyntaxGrep',
           'OnigEncodingEUC_KR', 'onig_region_new',
           'OnigEncodingUTF16_LE', 're_pattern_buffer',
           'onig_null_warn', 'OnigEncodingEUC_CN',
           'onig_noname_group_capture_is_active',
           'onig_set_syntax_behavior',
           'onig_get_match_stack_limit_size', 'onigenc_strlen_null',
           'OnigEncodingUTF32_BE', 'onig_end', 'OnigCodePoint',
           'OnigSyntaxPosixExtended', 'onigenc_get_prev_char_head',
           'onig_init', 'onig_set_verb_warn_func', 'onig_match',
           'onig_name_to_backref_number', 'OnigEncodingUTF8',
           'onig_get_syntax_op2', 'OnigDefaultSyntax',
           'onig_copyright', 'OnigEncodingASCII', 'OnigEncoding',
           'OnigUChar', 'onig_copy_syntax',
           'OnigCaptureTreeNodeStruct', 'onig_get_options',
           'onig_free', 'OnigEncodingUTF32_LE', 'OnigSyntaxPerl',
           'onigenc_init', 'OnigSyntaxType',
           'onigenc_get_default_encoding', 'onig_region_resize',
           'onigenc_strlen', 'OnigSyntaxEmacs', 'onig_region_clear',
           'onig_get_default_case_fold_flag',
           'onigenc_get_right_adjust_char_head', 'OnigErrorInfo',
           'OnigRegex', 'OnigRepeatRange',
           'onigenc_set_default_caseconv_table', 'OnigOptionType']
