# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/diego/Projects/prymatex/resources/ui/codeeditor/newstatus.ui'
#
# Created: Wed Sep 17 09:55:05 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CodeEditorStatus(object):
    def setupUi(self, CodeEditorStatus):
        CodeEditorStatus.setObjectName("CodeEditorStatus")
        CodeEditorStatus.resize(696, 230)
        self.verticalLayout = QtWidgets.QVBoxLayout(CodeEditorStatus)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetCommand = QtWidgets.QWidget(CodeEditorStatus)
        self.widgetCommand.setObjectName("widgetCommand")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetCommand)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxInput = QtWidgets.QComboBox(self.widgetCommand)
        self.comboBoxInput.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBoxInput.setObjectName("comboBoxInput")
        self.horizontalLayout.addWidget(self.comboBoxInput)
        self.line_4 = QtWidgets.QFrame(self.widgetCommand)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.comboBoxOutput = QtWidgets.QComboBox(self.widgetCommand)
        self.comboBoxOutput.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBoxOutput.setObjectName("comboBoxOutput")
        self.horizontalLayout.addWidget(self.comboBoxOutput)
        self.comboBoxCommand = QtWidgets.QComboBox(self.widgetCommand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand.setSizePolicy(sizePolicy)
        self.comboBoxCommand.setEditable(True)
        self.comboBoxCommand.setObjectName("comboBoxCommand")
        self.horizontalLayout.addWidget(self.comboBoxCommand)
        self.pushButtonCommandClose = QtWidgets.QPushButton(self.widgetCommand)
        self.pushButtonCommandClose.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonCommandClose.setText("")
        icon = QtGui.QIcon.fromTheme("close")
        self.pushButtonCommandClose.setIcon(icon)
        self.pushButtonCommandClose.setFlat(True)
        self.pushButtonCommandClose.setObjectName("pushButtonCommandClose")
        self.horizontalLayout.addWidget(self.pushButtonCommandClose)
        self.verticalLayout.addWidget(self.widgetCommand)
        self.widgetIFind = QtWidgets.QWidget(CodeEditorStatus)
        self.widgetIFind.setObjectName("widgetIFind")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widgetIFind)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButton_3.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.line = QtWidgets.QFrame(self.widgetIFind)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.pushButton_4 = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButton_4.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButton_5.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.line_2 = QtWidgets.QFrame(self.widgetIFind)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButton_6.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.comboBoxCommand_2 = QtWidgets.QComboBox(self.widgetIFind)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_2.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_2.setSizePolicy(sizePolicy)
        self.comboBoxCommand_2.setEditable(True)
        self.comboBoxCommand_2.setObjectName("comboBoxCommand_2")
        self.horizontalLayout_5.addWidget(self.comboBoxCommand_2)
        self.pushButtonIFindNext = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButtonIFindNext.setObjectName("pushButtonIFindNext")
        self.horizontalLayout_5.addWidget(self.pushButtonIFindNext)
        self.pushButtonIFindPrevious = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButtonIFindPrevious.setObjectName("pushButtonIFindPrevious")
        self.horizontalLayout_5.addWidget(self.pushButtonIFindPrevious)
        self.pushButtonFindAll_2 = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButtonFindAll_2.setObjectName("pushButtonFindAll_2")
        self.horizontalLayout_5.addWidget(self.pushButtonFindAll_2)
        self.pushButtonIFindClose = QtWidgets.QPushButton(self.widgetIFind)
        self.pushButtonIFindClose.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonIFindClose.setText("")
        icon = QtGui.QIcon.fromTheme("close")
        self.pushButtonIFindClose.setIcon(icon)
        self.pushButtonIFindClose.setFlat(True)
        self.pushButtonIFindClose.setObjectName("pushButtonIFindClose")
        self.horizontalLayout_5.addWidget(self.pushButtonIFindClose)
        self.verticalLayout.addWidget(self.widgetIFind)
        self.widgetFindReplace = QtWidgets.QWidget(CodeEditorStatus)
        self.widgetFindReplace.setObjectName("widgetFindReplace")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetFindReplace)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_10 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_10.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 4, 1, 1)
        self.labelFindMode_2 = QtWidgets.QLabel(self.widgetFindReplace)
        self.labelFindMode_2.setObjectName("labelFindMode_2")
        self.gridLayout.addWidget(self.labelFindMode_2, 1, 6, 1, 1)
        self.pushButtonReplace = QtWidgets.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme("replace")
        self.pushButtonReplace.setIcon(icon)
        self.pushButtonReplace.setObjectName("pushButtonReplace")
        self.gridLayout.addWidget(self.pushButtonReplace, 1, 8, 1, 1)
        self.pushButtonReplaceAll = QtWidgets.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme("replace-all")
        self.pushButtonReplaceAll.setIcon(icon)
        self.pushButtonReplaceAll.setObjectName("pushButtonReplaceAll")
        self.gridLayout.addWidget(self.pushButtonReplaceAll, 1, 9, 1, 1)
        self.pushButtonFindPrevious = QtWidgets.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme("go-up")
        self.pushButtonFindPrevious.setIcon(icon)
        self.pushButtonFindPrevious.setObjectName("pushButtonFindPrevious")
        self.gridLayout.addWidget(self.pushButtonFindPrevious, 0, 9, 1, 1)
        self.pushButtonFindNext = QtWidgets.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme("go-down")
        self.pushButtonFindNext.setIcon(icon)
        self.pushButtonFindNext.setObjectName("pushButtonFindNext")
        self.gridLayout.addWidget(self.pushButtonFindNext, 0, 8, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_11.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 5, 1, 1)
        self.labelFindMode_3 = QtWidgets.QLabel(self.widgetFindReplace)
        self.labelFindMode_3.setObjectName("labelFindMode_3")
        self.gridLayout.addWidget(self.labelFindMode_3, 0, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widgetFindReplace)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)
        self.comboBoxCommand_3 = QtWidgets.QComboBox(self.widgetFindReplace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_3.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_3.setSizePolicy(sizePolicy)
        self.comboBoxCommand_3.setEditable(True)
        self.comboBoxCommand_3.setObjectName("comboBoxCommand_3")
        self.gridLayout.addWidget(self.comboBoxCommand_3, 0, 7, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_9.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_8.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButtonFindReplaceClose = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButtonFindReplaceClose.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonFindReplaceClose.setText("")
        icon = QtGui.QIcon.fromTheme("close")
        self.pushButtonFindReplaceClose.setIcon(icon)
        self.pushButtonFindReplaceClose.setFlat(True)
        self.pushButtonFindReplaceClose.setObjectName("pushButtonFindReplaceClose")
        self.gridLayout.addWidget(self.pushButtonFindReplaceClose, 0, 10, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_12.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_7.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.comboBoxCommand_4 = QtWidgets.QComboBox(self.widgetFindReplace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_4.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_4.setSizePolicy(sizePolicy)
        self.comboBoxCommand_4.setEditable(True)
        self.comboBoxCommand_4.setObjectName("comboBoxCommand_4")
        self.gridLayout.addWidget(self.comboBoxCommand_4, 1, 7, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widgetFindReplace)
        self.pushButton_13.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widgetFindReplace)
        self.widgetFindReplace_2 = QtWidgets.QWidget(CodeEditorStatus)
        self.widgetFindReplace_2.setObjectName("widgetFindReplace_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetFindReplace_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonFindReplaceClose_2 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        self.pushButtonFindReplaceClose_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonFindReplaceClose_2.setText("")
        icon = QtGui.QIcon.fromTheme("close")
        self.pushButtonFindReplaceClose_2.setIcon(icon)
        self.pushButtonFindReplaceClose_2.setFlat(True)
        self.pushButtonFindReplaceClose_2.setObjectName("pushButtonFindReplaceClose_2")
        self.gridLayout_2.addWidget(self.pushButtonFindReplaceClose_2, 0, 9, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        self.pushButton_15.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 0, 4, 1, 1)
        self.labelFindMode_6 = QtWidgets.QLabel(self.widgetFindReplace_2)
        self.labelFindMode_6.setObjectName("labelFindMode_6")
        self.gridLayout_2.addWidget(self.labelFindMode_6, 2, 5, 1, 1)
        self.pushButtonReplaceAll_2 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme("replace-all")
        self.pushButtonReplaceAll_2.setIcon(icon)
        self.pushButtonReplaceAll_2.setObjectName("pushButtonReplaceAll_2")
        self.gridLayout_2.addWidget(self.pushButtonReplaceAll_2, 1, 8, 1, 1)
        self.labelFindMode_5 = QtWidgets.QLabel(self.widgetFindReplace_2)
        self.labelFindMode_5.setObjectName("labelFindMode_5")
        self.gridLayout_2.addWidget(self.labelFindMode_5, 0, 5, 1, 1)
        self.labelFindMode_4 = QtWidgets.QLabel(self.widgetFindReplace_2)
        self.labelFindMode_4.setObjectName("labelFindMode_4")
        self.gridLayout_2.addWidget(self.labelFindMode_4, 1, 5, 1, 1)
        self.pushButtonFindPrevious_2 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme("go-up")
        self.pushButtonFindPrevious_2.setIcon(icon)
        self.pushButtonFindPrevious_2.setObjectName("pushButtonFindPrevious_2")
        self.gridLayout_2.addWidget(self.pushButtonFindPrevious_2, 0, 8, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        self.pushButton_16.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 0, 2, 1, 1)
        self.comboBoxCommand_7 = QtWidgets.QComboBox(self.widgetFindReplace_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_7.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_7.setSizePolicy(sizePolicy)
        self.comboBoxCommand_7.setEditable(True)
        self.comboBoxCommand_7.setObjectName("comboBoxCommand_7")
        self.gridLayout_2.addWidget(self.comboBoxCommand_7, 2, 6, 1, 1)
        self.comboBoxCommand_5 = QtWidgets.QComboBox(self.widgetFindReplace_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_5.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_5.setSizePolicy(sizePolicy)
        self.comboBoxCommand_5.setEditable(True)
        self.comboBoxCommand_5.setObjectName("comboBoxCommand_5")
        self.gridLayout_2.addWidget(self.comboBoxCommand_5, 0, 6, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        self.pushButton_19.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        self.pushButton_14.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 0, 3, 1, 1)
        self.pushButtonReplace_2 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme("replace")
        self.pushButtonReplace_2.setIcon(icon)
        self.pushButtonReplace_2.setObjectName("pushButtonReplace_2")
        self.gridLayout_2.addWidget(self.pushButtonReplace_2, 1, 7, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        self.pushButton_17.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 0, 1, 1, 1)
        self.comboBoxCommand_6 = QtWidgets.QComboBox(self.widgetFindReplace_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_6.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_6.setSizePolicy(sizePolicy)
        self.comboBoxCommand_6.setEditable(True)
        self.comboBoxCommand_6.setObjectName("comboBoxCommand_6")
        self.gridLayout_2.addWidget(self.comboBoxCommand_6, 1, 6, 1, 1)
        self.pushButtonFindNext_2 = QtWidgets.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme("go-down")
        self.pushButtonFindNext_2.setIcon(icon)
        self.pushButtonFindNext_2.setObjectName("pushButtonFindNext_2")
        self.gridLayout_2.addWidget(self.pushButtonFindNext_2, 0, 7, 1, 1)
        self.verticalLayout.addWidget(self.widgetFindReplace_2)
        self.widgetStatus = QtWidgets.QWidget(CodeEditorStatus)
        self.widgetStatus.setObjectName("widgetStatus")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetStatus)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPosition = QtWidgets.QLabel(self.widgetStatus)
        self.labelPosition.setMaximumSize(QtCore.QSize(300, 16777215))
        self.labelPosition.setObjectName("labelPosition")
        self.horizontalLayout_2.addWidget(self.labelPosition)
        self.line_5 = QtWidgets.QFrame(self.widgetStatus)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.labelContent = QtWidgets.QLabel(self.widgetStatus)
        self.labelContent.setMaximumSize(QtCore.QSize(350, 16777215))
        self.labelContent.setObjectName("labelContent")
        self.horizontalLayout_2.addWidget(self.labelContent)
        self.line_6 = QtWidgets.QFrame(self.widgetStatus)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.labelStatus = QtWidgets.QLabel(self.widgetStatus)
        self.labelStatus.setMaximumSize(QtCore.QSize(150, 16777215))
        self.labelStatus.setObjectName("labelStatus")
        self.horizontalLayout_2.addWidget(self.labelStatus)
        self.toolButtonMenuBundle = QtWidgets.QToolButton(self.widgetStatus)
        icon = QtGui.QIcon.fromTheme("cogs")
        self.toolButtonMenuBundle.setIcon(icon)
        self.toolButtonMenuBundle.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonMenuBundle.setAutoRaise(True)
        self.toolButtonMenuBundle.setObjectName("toolButtonMenuBundle")
        self.horizontalLayout_2.addWidget(self.toolButtonMenuBundle)
        self.comboBoxSyntaxes = QtWidgets.QComboBox(self.widgetStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSyntaxes.sizePolicy().hasHeightForWidth())
        self.comboBoxSyntaxes.setSizePolicy(sizePolicy)
        self.comboBoxSyntaxes.setObjectName("comboBoxSyntaxes")
        self.horizontalLayout_2.addWidget(self.comboBoxSyntaxes)
        self.comboBoxSymbols = QtWidgets.QComboBox(self.widgetStatus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSymbols.sizePolicy().hasHeightForWidth())
        self.comboBoxSymbols.setSizePolicy(sizePolicy)
        self.comboBoxSymbols.setObjectName("comboBoxSymbols")
        self.horizontalLayout_2.addWidget(self.comboBoxSymbols)
        self.verticalLayout.addWidget(self.widgetStatus)

        self.retranslateUi(CodeEditorStatus)
        QtCore.QMetaObject.connectSlotsByName(CodeEditorStatus)

    def retranslateUi(self, CodeEditorStatus):
        _translate = QtCore.QCoreApplication.translate
        CodeEditorStatus.setWindowTitle(_translate("CodeEditorStatus", "Form"))
        self.pushButton.setText(_translate("CodeEditorStatus", ".*"))
        self.pushButton_2.setText(_translate("CodeEditorStatus", "Aa"))
        self.pushButton_3.setText(_translate("CodeEditorStatus", "\"\""))
        self.pushButtonIFindNext.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find Previous</p></body></html>"))
        self.pushButtonIFindNext.setText(_translate("CodeEditorStatus", "Find"))
        self.pushButtonIFindPrevious.setText(_translate("CodeEditorStatus", "Find Prev"))
        self.pushButtonFindAll_2.setText(_translate("CodeEditorStatus", "Find All"))
        self.labelFindMode_2.setText(_translate("CodeEditorStatus", "With:"))
        self.pushButtonReplace.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Replace &amp; Find Previous</p></body></html>"))
        self.pushButtonReplace.setText(_translate("CodeEditorStatus", "Replace"))
        self.pushButtonReplaceAll.setText(_translate("CodeEditorStatus", "Replace &All"))
        self.pushButtonFindPrevious.setText(_translate("CodeEditorStatus", "Previous"))
        self.pushButtonFindNext.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find Previous</p></body></html>"))
        self.pushButtonFindNext.setText(_translate("CodeEditorStatus", "Next"))
        self.labelFindMode_3.setText(_translate("CodeEditorStatus", "What:"))
        self.pushButton_9.setText(_translate("CodeEditorStatus", "\"\""))
        self.pushButton_8.setText(_translate("CodeEditorStatus", "Aa"))
        self.pushButton_7.setText(_translate("CodeEditorStatus", ".*"))
        self.pushButton_13.setText(_translate("CodeEditorStatus", "Aa"))
        self.labelFindMode_6.setText(_translate("CodeEditorStatus", "Replace:"))
        self.pushButtonReplaceAll_2.setText(_translate("CodeEditorStatus", "Replace &All"))
        self.labelFindMode_5.setText(_translate("CodeEditorStatus", "What:"))
        self.labelFindMode_4.setText(_translate("CodeEditorStatus", "Where:"))
        self.pushButtonFindPrevious_2.setText(_translate("CodeEditorStatus", "Previous"))
        self.pushButton_16.setText(_translate("CodeEditorStatus", "\"\""))
        self.pushButton_19.setText(_translate("CodeEditorStatus", ".*"))
        self.pushButtonReplace_2.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Replace &amp; Find Previous</p></body></html>"))
        self.pushButtonReplace_2.setText(_translate("CodeEditorStatus", "Replace"))
        self.pushButton_17.setText(_translate("CodeEditorStatus", "Aa"))
        self.pushButtonFindNext_2.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find Previous</p></body></html>"))
        self.pushButtonFindNext_2.setText(_translate("CodeEditorStatus", "Next"))
        self.labelPosition.setText(_translate("CodeEditorStatus", "Position"))
        self.labelContent.setText(_translate("CodeEditorStatus", "Content"))
        self.labelStatus.setText(_translate("CodeEditorStatus", "Status"))

