# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/diego/Projects/prymatex/resources/ui/codeeditor/newstatus.ui'
#
# Created: Thu Sep 18 10:11:59 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CodeEditorStatus(object):
    def setupUi(self, CodeEditorStatus):
        CodeEditorStatus.setObjectName(_fromUtf8("CodeEditorStatus"))
        CodeEditorStatus.resize(696, 230)
        self.verticalLayout = QtGui.QVBoxLayout(CodeEditorStatus)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widgetCommand = QtGui.QWidget(CodeEditorStatus)
        self.widgetCommand.setObjectName(_fromUtf8("widgetCommand"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widgetCommand)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboBoxInput = QtGui.QComboBox(self.widgetCommand)
        self.comboBoxInput.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBoxInput.setObjectName(_fromUtf8("comboBoxInput"))
        self.horizontalLayout.addWidget(self.comboBoxInput)
        self.line_4 = QtGui.QFrame(self.widgetCommand)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.comboBoxOutput = QtGui.QComboBox(self.widgetCommand)
        self.comboBoxOutput.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBoxOutput.setObjectName(_fromUtf8("comboBoxOutput"))
        self.horizontalLayout.addWidget(self.comboBoxOutput)
        self.comboBoxCommand = QtGui.QComboBox(self.widgetCommand)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand.setSizePolicy(sizePolicy)
        self.comboBoxCommand.setEditable(True)
        self.comboBoxCommand.setObjectName(_fromUtf8("comboBoxCommand"))
        self.horizontalLayout.addWidget(self.comboBoxCommand)
        self.pushButtonCommandClose = QtGui.QPushButton(self.widgetCommand)
        self.pushButtonCommandClose.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonCommandClose.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("close"))
        self.pushButtonCommandClose.setIcon(icon)
        self.pushButtonCommandClose.setFlat(True)
        self.pushButtonCommandClose.setObjectName(_fromUtf8("pushButtonCommandClose"))
        self.horizontalLayout.addWidget(self.pushButtonCommandClose)
        self.verticalLayout.addWidget(self.widgetCommand)
        self.widgetIFind = QtGui.QWidget(CodeEditorStatus)
        self.widgetIFind.setObjectName(_fromUtf8("widgetIFind"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widgetIFind)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.widgetIFind)
        self.pushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.widgetIFind)
        self.pushButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.widgetIFind)
        self.pushButton_3.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.line = QtGui.QFrame(self.widgetIFind)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.pushButton_4 = QtGui.QPushButton(self.widgetIFind)
        self.pushButton_4.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widgetIFind)
        self.pushButton_5.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.line_2 = QtGui.QFrame(self.widgetIFind)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_5.addWidget(self.line_2)
        self.pushButton_6 = QtGui.QPushButton(self.widgetIFind)
        self.pushButton_6.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.comboBoxCommand_2 = QtGui.QComboBox(self.widgetIFind)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_2.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_2.setSizePolicy(sizePolicy)
        self.comboBoxCommand_2.setEditable(True)
        self.comboBoxCommand_2.setObjectName(_fromUtf8("comboBoxCommand_2"))
        self.horizontalLayout_5.addWidget(self.comboBoxCommand_2)
        self.pushButtonIFindNext = QtGui.QPushButton(self.widgetIFind)
        self.pushButtonIFindNext.setObjectName(_fromUtf8("pushButtonIFindNext"))
        self.horizontalLayout_5.addWidget(self.pushButtonIFindNext)
        self.pushButtonIFindPrevious = QtGui.QPushButton(self.widgetIFind)
        self.pushButtonIFindPrevious.setObjectName(_fromUtf8("pushButtonIFindPrevious"))
        self.horizontalLayout_5.addWidget(self.pushButtonIFindPrevious)
        self.pushButtonFindAll_2 = QtGui.QPushButton(self.widgetIFind)
        self.pushButtonFindAll_2.setObjectName(_fromUtf8("pushButtonFindAll_2"))
        self.horizontalLayout_5.addWidget(self.pushButtonFindAll_2)
        self.pushButtonIFindClose = QtGui.QPushButton(self.widgetIFind)
        self.pushButtonIFindClose.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonIFindClose.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("close"))
        self.pushButtonIFindClose.setIcon(icon)
        self.pushButtonIFindClose.setFlat(True)
        self.pushButtonIFindClose.setObjectName(_fromUtf8("pushButtonIFindClose"))
        self.horizontalLayout_5.addWidget(self.pushButtonIFindClose)
        self.verticalLayout.addWidget(self.widgetIFind)
        self.widgetFindReplace = QtGui.QWidget(CodeEditorStatus)
        self.widgetFindReplace.setObjectName(_fromUtf8("widgetFindReplace"))
        self.gridLayout = QtGui.QGridLayout(self.widgetFindReplace)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_10 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_10.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout.addWidget(self.pushButton_10, 0, 4, 1, 1)
        self.labelFindMode_2 = QtGui.QLabel(self.widgetFindReplace)
        self.labelFindMode_2.setObjectName(_fromUtf8("labelFindMode_2"))
        self.gridLayout.addWidget(self.labelFindMode_2, 1, 6, 1, 1)
        self.pushButtonReplace = QtGui.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("replace"))
        self.pushButtonReplace.setIcon(icon)
        self.pushButtonReplace.setObjectName(_fromUtf8("pushButtonReplace"))
        self.gridLayout.addWidget(self.pushButtonReplace, 1, 8, 1, 1)
        self.pushButtonReplaceAll = QtGui.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("replace-all"))
        self.pushButtonReplaceAll.setIcon(icon)
        self.pushButtonReplaceAll.setObjectName(_fromUtf8("pushButtonReplaceAll"))
        self.gridLayout.addWidget(self.pushButtonReplaceAll, 1, 9, 1, 1)
        self.pushButtonFindPrevious = QtGui.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-up"))
        self.pushButtonFindPrevious.setIcon(icon)
        self.pushButtonFindPrevious.setObjectName(_fromUtf8("pushButtonFindPrevious"))
        self.gridLayout.addWidget(self.pushButtonFindPrevious, 0, 9, 1, 1)
        self.pushButtonFindNext = QtGui.QPushButton(self.widgetFindReplace)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-down"))
        self.pushButtonFindNext.setIcon(icon)
        self.pushButtonFindNext.setObjectName(_fromUtf8("pushButtonFindNext"))
        self.gridLayout.addWidget(self.pushButtonFindNext, 0, 8, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_11.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_11.setText(_fromUtf8(""))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout.addWidget(self.pushButton_11, 0, 5, 1, 1)
        self.labelFindMode_3 = QtGui.QLabel(self.widgetFindReplace)
        self.labelFindMode_3.setObjectName(_fromUtf8("labelFindMode_3"))
        self.gridLayout.addWidget(self.labelFindMode_3, 0, 6, 1, 1)
        self.line_3 = QtGui.QFrame(self.widgetFindReplace)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)
        self.comboBoxCommand_3 = QtGui.QComboBox(self.widgetFindReplace)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_3.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_3.setSizePolicy(sizePolicy)
        self.comboBoxCommand_3.setEditable(True)
        self.comboBoxCommand_3.setObjectName(_fromUtf8("comboBoxCommand_3"))
        self.gridLayout.addWidget(self.comboBoxCommand_3, 0, 7, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_9.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_8.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButtonFindReplaceClose = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButtonFindReplaceClose.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonFindReplaceClose.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("close"))
        self.pushButtonFindReplaceClose.setIcon(icon)
        self.pushButtonFindReplaceClose.setFlat(True)
        self.pushButtonFindReplaceClose.setObjectName(_fromUtf8("pushButtonFindReplaceClose"))
        self.gridLayout.addWidget(self.pushButtonFindReplaceClose, 0, 10, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_12.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_12.setText(_fromUtf8(""))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout.addWidget(self.pushButton_12, 1, 4, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_7.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.comboBoxCommand_4 = QtGui.QComboBox(self.widgetFindReplace)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_4.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_4.setSizePolicy(sizePolicy)
        self.comboBoxCommand_4.setEditable(True)
        self.comboBoxCommand_4.setObjectName(_fromUtf8("comboBoxCommand_4"))
        self.gridLayout.addWidget(self.comboBoxCommand_4, 1, 7, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.widgetFindReplace)
        self.pushButton_13.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widgetFindReplace)
        self.widgetFindReplace_2 = QtGui.QWidget(CodeEditorStatus)
        self.widgetFindReplace_2.setObjectName(_fromUtf8("widgetFindReplace_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widgetFindReplace_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonFindReplaceClose_2 = QtGui.QPushButton(self.widgetFindReplace_2)
        self.pushButtonFindReplaceClose_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonFindReplaceClose_2.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("close"))
        self.pushButtonFindReplaceClose_2.setIcon(icon)
        self.pushButtonFindReplaceClose_2.setFlat(True)
        self.pushButtonFindReplaceClose_2.setObjectName(_fromUtf8("pushButtonFindReplaceClose_2"))
        self.gridLayout_2.addWidget(self.pushButtonFindReplaceClose_2, 0, 9, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.widgetFindReplace_2)
        self.pushButton_15.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_15.setText(_fromUtf8(""))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_2.addWidget(self.pushButton_15, 0, 4, 1, 1)
        self.labelFindMode_6 = QtGui.QLabel(self.widgetFindReplace_2)
        self.labelFindMode_6.setObjectName(_fromUtf8("labelFindMode_6"))
        self.gridLayout_2.addWidget(self.labelFindMode_6, 2, 5, 1, 1)
        self.pushButtonReplaceAll_2 = QtGui.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("replace-all"))
        self.pushButtonReplaceAll_2.setIcon(icon)
        self.pushButtonReplaceAll_2.setObjectName(_fromUtf8("pushButtonReplaceAll_2"))
        self.gridLayout_2.addWidget(self.pushButtonReplaceAll_2, 1, 8, 1, 1)
        self.labelFindMode_5 = QtGui.QLabel(self.widgetFindReplace_2)
        self.labelFindMode_5.setObjectName(_fromUtf8("labelFindMode_5"))
        self.gridLayout_2.addWidget(self.labelFindMode_5, 0, 5, 1, 1)
        self.labelFindMode_4 = QtGui.QLabel(self.widgetFindReplace_2)
        self.labelFindMode_4.setObjectName(_fromUtf8("labelFindMode_4"))
        self.gridLayout_2.addWidget(self.labelFindMode_4, 1, 5, 1, 1)
        self.pushButtonFindPrevious_2 = QtGui.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-up"))
        self.pushButtonFindPrevious_2.setIcon(icon)
        self.pushButtonFindPrevious_2.setObjectName(_fromUtf8("pushButtonFindPrevious_2"))
        self.gridLayout_2.addWidget(self.pushButtonFindPrevious_2, 0, 8, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.widgetFindReplace_2)
        self.pushButton_16.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_2.addWidget(self.pushButton_16, 0, 2, 1, 1)
        self.comboBoxCommand_7 = QtGui.QComboBox(self.widgetFindReplace_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_7.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_7.setSizePolicy(sizePolicy)
        self.comboBoxCommand_7.setEditable(True)
        self.comboBoxCommand_7.setObjectName(_fromUtf8("comboBoxCommand_7"))
        self.gridLayout_2.addWidget(self.comboBoxCommand_7, 2, 6, 1, 1)
        self.comboBoxCommand_5 = QtGui.QComboBox(self.widgetFindReplace_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_5.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_5.setSizePolicy(sizePolicy)
        self.comboBoxCommand_5.setEditable(True)
        self.comboBoxCommand_5.setObjectName(_fromUtf8("comboBoxCommand_5"))
        self.gridLayout_2.addWidget(self.comboBoxCommand_5, 0, 6, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.widgetFindReplace_2)
        self.pushButton_19.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_2.addWidget(self.pushButton_19, 0, 0, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.widgetFindReplace_2)
        self.pushButton_14.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_14.setText(_fromUtf8(""))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_2.addWidget(self.pushButton_14, 0, 3, 1, 1)
        self.pushButtonReplace_2 = QtGui.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("replace"))
        self.pushButtonReplace_2.setIcon(icon)
        self.pushButtonReplace_2.setObjectName(_fromUtf8("pushButtonReplace_2"))
        self.gridLayout_2.addWidget(self.pushButtonReplace_2, 1, 7, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.widgetFindReplace_2)
        self.pushButton_17.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_2.addWidget(self.pushButton_17, 0, 1, 1, 1)
        self.comboBoxCommand_6 = QtGui.QComboBox(self.widgetFindReplace_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCommand_6.sizePolicy().hasHeightForWidth())
        self.comboBoxCommand_6.setSizePolicy(sizePolicy)
        self.comboBoxCommand_6.setEditable(True)
        self.comboBoxCommand_6.setObjectName(_fromUtf8("comboBoxCommand_6"))
        self.gridLayout_2.addWidget(self.comboBoxCommand_6, 1, 6, 1, 1)
        self.pushButtonFindNext_2 = QtGui.QPushButton(self.widgetFindReplace_2)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-down"))
        self.pushButtonFindNext_2.setIcon(icon)
        self.pushButtonFindNext_2.setObjectName(_fromUtf8("pushButtonFindNext_2"))
        self.gridLayout_2.addWidget(self.pushButtonFindNext_2, 0, 7, 1, 1)
        self.verticalLayout.addWidget(self.widgetFindReplace_2)
        self.widgetStatus = QtGui.QWidget(CodeEditorStatus)
        self.widgetStatus.setObjectName(_fromUtf8("widgetStatus"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widgetStatus)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelPosition = QtGui.QLabel(self.widgetStatus)
        self.labelPosition.setMaximumSize(QtCore.QSize(300, 16777215))
        self.labelPosition.setObjectName(_fromUtf8("labelPosition"))
        self.horizontalLayout_2.addWidget(self.labelPosition)
        self.line_5 = QtGui.QFrame(self.widgetStatus)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_2.addWidget(self.line_5)
        self.labelContent = QtGui.QLabel(self.widgetStatus)
        self.labelContent.setMaximumSize(QtCore.QSize(350, 16777215))
        self.labelContent.setObjectName(_fromUtf8("labelContent"))
        self.horizontalLayout_2.addWidget(self.labelContent)
        self.line_6 = QtGui.QFrame(self.widgetStatus)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_2.addWidget(self.line_6)
        self.labelStatus = QtGui.QLabel(self.widgetStatus)
        self.labelStatus.setMaximumSize(QtCore.QSize(150, 16777215))
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.horizontalLayout_2.addWidget(self.labelStatus)
        self.toolButtonMenuBundle = QtGui.QToolButton(self.widgetStatus)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("cogs"))
        self.toolButtonMenuBundle.setIcon(icon)
        self.toolButtonMenuBundle.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.toolButtonMenuBundle.setAutoRaise(True)
        self.toolButtonMenuBundle.setObjectName(_fromUtf8("toolButtonMenuBundle"))
        self.horizontalLayout_2.addWidget(self.toolButtonMenuBundle)
        self.comboBoxSyntaxes = QtGui.QComboBox(self.widgetStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSyntaxes.sizePolicy().hasHeightForWidth())
        self.comboBoxSyntaxes.setSizePolicy(sizePolicy)
        self.comboBoxSyntaxes.setObjectName(_fromUtf8("comboBoxSyntaxes"))
        self.horizontalLayout_2.addWidget(self.comboBoxSyntaxes)
        self.comboBoxSymbols = QtGui.QComboBox(self.widgetStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSymbols.sizePolicy().hasHeightForWidth())
        self.comboBoxSymbols.setSizePolicy(sizePolicy)
        self.comboBoxSymbols.setObjectName(_fromUtf8("comboBoxSymbols"))
        self.horizontalLayout_2.addWidget(self.comboBoxSymbols)
        self.verticalLayout.addWidget(self.widgetStatus)

        self.retranslateUi(CodeEditorStatus)
        QtCore.QMetaObject.connectSlotsByName(CodeEditorStatus)

    def retranslateUi(self, CodeEditorStatus):
        CodeEditorStatus.setWindowTitle(_translate("CodeEditorStatus", "Form", None))
        self.pushButton.setText(_translate("CodeEditorStatus", ".*", None))
        self.pushButton_2.setText(_translate("CodeEditorStatus", "Aa", None))
        self.pushButton_3.setText(_translate("CodeEditorStatus", "\"\"", None))
        self.pushButtonIFindNext.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find Previous</p></body></html>", None))
        self.pushButtonIFindNext.setText(_translate("CodeEditorStatus", "Find", None))
        self.pushButtonIFindPrevious.setText(_translate("CodeEditorStatus", "Find Prev", None))
        self.pushButtonFindAll_2.setText(_translate("CodeEditorStatus", "Find All", None))
        self.labelFindMode_2.setText(_translate("CodeEditorStatus", "With:", None))
        self.pushButtonReplace.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Replace &amp; Find Previous</p></body></html>", None))
        self.pushButtonReplace.setText(_translate("CodeEditorStatus", "Replace", None))
        self.pushButtonReplaceAll.setText(_translate("CodeEditorStatus", "Replace &All", None))
        self.pushButtonFindPrevious.setText(_translate("CodeEditorStatus", "Previous", None))
        self.pushButtonFindNext.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find Previous</p></body></html>", None))
        self.pushButtonFindNext.setText(_translate("CodeEditorStatus", "Next", None))
        self.labelFindMode_3.setText(_translate("CodeEditorStatus", "What:", None))
        self.pushButton_9.setText(_translate("CodeEditorStatus", "\"\"", None))
        self.pushButton_8.setText(_translate("CodeEditorStatus", "Aa", None))
        self.pushButton_7.setText(_translate("CodeEditorStatus", ".*", None))
        self.pushButton_13.setText(_translate("CodeEditorStatus", "Aa", None))
        self.labelFindMode_6.setText(_translate("CodeEditorStatus", "Replace:", None))
        self.pushButtonReplaceAll_2.setText(_translate("CodeEditorStatus", "Replace &All", None))
        self.labelFindMode_5.setText(_translate("CodeEditorStatus", "What:", None))
        self.labelFindMode_4.setText(_translate("CodeEditorStatus", "Where:", None))
        self.pushButtonFindPrevious_2.setText(_translate("CodeEditorStatus", "Previous", None))
        self.pushButton_16.setText(_translate("CodeEditorStatus", "\"\"", None))
        self.pushButton_19.setText(_translate("CodeEditorStatus", ".*", None))
        self.pushButtonReplace_2.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Replace &amp; Find Previous</p></body></html>", None))
        self.pushButtonReplace_2.setText(_translate("CodeEditorStatus", "Replace", None))
        self.pushButton_17.setText(_translate("CodeEditorStatus", "Aa", None))
        self.pushButtonFindNext_2.setToolTip(_translate("CodeEditorStatus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Find Previous</p></body></html>", None))
        self.pushButtonFindNext_2.setText(_translate("CodeEditorStatus", "Next", None))
        self.labelPosition.setText(_translate("CodeEditorStatus", "Position", None))
        self.labelContent.setText(_translate("CodeEditorStatus", "Content", None))
        self.labelStatus.setText(_translate("CodeEditorStatus", "Status", None))

