# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/likewise-open/SUPTRIB/dvanhaaster/Workspace/prymatex/resources/ui/dockers/filesystem.ui'
#
# Created: Tue Jul 30 11:12:01 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FileSystemDock(object):
    def setupUi(self, FileSystemDock):
        FileSystemDock.setObjectName(_fromUtf8("FileSystemDock"))
        FileSystemDock.resize(330, 484)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buttonsLayout = QtGui.QHBoxLayout()
        self.buttonsLayout.setSpacing(2)
        self.buttonsLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.buttonsLayout.setObjectName(_fromUtf8("buttonsLayout"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.pushButtonBack = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonBack.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-previous"))
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.buttonsLayout.addWidget(self.pushButtonBack)
        self.pushButtonFoward = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonFoward.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-next"))
        self.pushButtonFoward.setIcon(icon)
        self.pushButtonFoward.setFlat(True)
        self.pushButtonFoward.setObjectName(_fromUtf8("pushButtonFoward"))
        self.buttonsLayout.addWidget(self.pushButtonFoward)
        self.pushButtonUp = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonUp.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-up"))
        self.pushButtonUp.setIcon(icon)
        self.pushButtonUp.setFlat(True)
        self.pushButtonUp.setObjectName(_fromUtf8("pushButtonUp"))
        self.buttonsLayout.addWidget(self.pushButtonUp)
        self.line = QtGui.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.buttonsLayout.addWidget(self.line)
        self.pushButtonSync = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonSync.setMaximumSize(QtCore.QSize(24, 24))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder-sync"))
        self.pushButtonSync.setIcon(icon)
        self.pushButtonSync.setCheckable(True)
        self.pushButtonSync.setFlat(True)
        self.pushButtonSync.setObjectName(_fromUtf8("pushButtonSync"))
        self.buttonsLayout.addWidget(self.pushButtonSync)
        self.pushButtonCollapseAll = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonCollapseAll.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonCollapseAll.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-list-tree"))
        self.pushButtonCollapseAll.setIcon(icon)
        self.pushButtonCollapseAll.setFlat(True)
        self.pushButtonCollapseAll.setObjectName(_fromUtf8("pushButtonCollapseAll"))
        self.buttonsLayout.addWidget(self.pushButtonCollapseAll)
        self.pushButtonCustomFilters = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonCustomFilters.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonCustomFilters.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-filter"))
        self.pushButtonCustomFilters.setIcon(icon)
        self.pushButtonCustomFilters.setFlat(True)
        self.pushButtonCustomFilters.setObjectName(_fromUtf8("pushButtonCustomFilters"))
        self.buttonsLayout.addWidget(self.pushButtonCustomFilters)
        self.pushButtonOptions = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButtonOptions.setMaximumSize(QtCore.QSize(45, 24))
        self.pushButtonOptions.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("configure"))
        self.pushButtonOptions.setIcon(icon)
        self.pushButtonOptions.setFlat(True)
        self.pushButtonOptions.setObjectName(_fromUtf8("pushButtonOptions"))
        self.buttonsLayout.addWidget(self.pushButtonOptions)
        self.verticalLayout.addLayout(self.buttonsLayout)
        self.comboBoxLocation = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLocation.sizePolicy().hasHeightForWidth())
        self.comboBoxLocation.setSizePolicy(sizePolicy)
        self.comboBoxLocation.setEditable(True)
        self.comboBoxLocation.setObjectName(_fromUtf8("comboBoxLocation"))
        self.verticalLayout.addWidget(self.comboBoxLocation)
        self.treeViewFileSystem = QtGui.QTreeView(self.dockWidgetContents)
        self.treeViewFileSystem.setObjectName(_fromUtf8("treeViewFileSystem"))
        self.verticalLayout.addWidget(self.treeViewFileSystem)
        FileSystemDock.setWidget(self.dockWidgetContents)
        self.actionNewFile = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.actionNewFile.setIcon(icon)
        self.actionNewFile.setObjectName(_fromUtf8("actionNewFile"))
        self.actionNewFolder = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder-new"))
        self.actionNewFolder.setIcon(icon)
        self.actionNewFolder.setObjectName(_fromUtf8("actionNewFolder"))
        self.actionNewFromTemplate = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/run-build-file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFromTemplate.setIcon(icon)
        self.actionNewFromTemplate.setObjectName(_fromUtf8("actionNewFromTemplate"))
        self.actionDelete = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.actionDelete.setIcon(icon)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionOrderByName = QtGui.QAction(FileSystemDock)
        self.actionOrderByName.setCheckable(True)
        self.actionOrderByName.setObjectName(_fromUtf8("actionOrderByName"))
        self.actionOrderBySize = QtGui.QAction(FileSystemDock)
        self.actionOrderBySize.setCheckable(True)
        self.actionOrderBySize.setObjectName(_fromUtf8("actionOrderBySize"))
        self.actionOrderByDate = QtGui.QAction(FileSystemDock)
        self.actionOrderByDate.setCheckable(True)
        self.actionOrderByDate.setObjectName(_fromUtf8("actionOrderByDate"))
        self.actionOrderByType = QtGui.QAction(FileSystemDock)
        self.actionOrderByType.setCheckable(True)
        self.actionOrderByType.setObjectName(_fromUtf8("actionOrderByType"))
        self.actionOrderDescending = QtGui.QAction(FileSystemDock)
        self.actionOrderDescending.setCheckable(True)
        self.actionOrderDescending.setObjectName(_fromUtf8("actionOrderDescending"))
        self.actionOrderFoldersFirst = QtGui.QAction(FileSystemDock)
        self.actionOrderFoldersFirst.setCheckable(True)
        self.actionOrderFoldersFirst.setObjectName(_fromUtf8("actionOrderFoldersFirst"))
        self.actionOpen = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpenSystemEditor = QtGui.QAction(FileSystemDock)
        self.actionOpenSystemEditor.setObjectName(_fromUtf8("actionOpenSystemEditor"))
        self.actionOpenDefaultEditor = QtGui.QAction(FileSystemDock)
        self.actionOpenDefaultEditor.setObjectName(_fromUtf8("actionOpenDefaultEditor"))
        self.actionRename = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-rename"))
        self.actionRename.setIcon(icon)
        self.actionRename.setObjectName(_fromUtf8("actionRename"))
        self.actionConvertIntoProject = QtGui.QAction(FileSystemDock)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvertIntoProject.setIcon(icon1)
        self.actionConvertIntoProject.setObjectName(_fromUtf8("actionConvertIntoProject"))
        self.actionSetInTerminal = QtGui.QAction(FileSystemDock)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/apps/utilities-terminal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetInTerminal.setIcon(icon2)
        self.actionSetInTerminal.setObjectName(_fromUtf8("actionSetInTerminal"))
        self.actionCut = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-cut"))
        self.actionCut.setIcon(icon)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-copy"))
        self.actionCopy.setIcon(icon)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(FileSystemDock)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-paste"))
        self.actionPaste.setIcon(icon)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))

        self.retranslateUi(FileSystemDock)
        QtCore.QMetaObject.connectSlotsByName(FileSystemDock)

    def retranslateUi(self, FileSystemDock):
        FileSystemDock.setWindowTitle(QtGui.QApplication.translate("FileSystemDock", "File System", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBack.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Go previous place", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFoward.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Go next place", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUp.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Go up one level", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSync.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Sync folder with current editor file path", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLocation.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewFile.setText(QtGui.QApplication.translate("FileSystemDock", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewFolder.setText(QtGui.QApplication.translate("FileSystemDock", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewFromTemplate.setText(QtGui.QApplication.translate("FileSystemDock", "File From Template", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewFromTemplate.setToolTip(QtGui.QApplication.translate("FileSystemDock", "File From Template", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("FileSystemDock", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrderByName.setText(QtGui.QApplication.translate("FileSystemDock", "By Name", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrderBySize.setText(QtGui.QApplication.translate("FileSystemDock", "By Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrderByDate.setText(QtGui.QApplication.translate("FileSystemDock", "By Date", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrderByType.setText(QtGui.QApplication.translate("FileSystemDock", "By Type", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrderDescending.setText(QtGui.QApplication.translate("FileSystemDock", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOrderFoldersFirst.setText(QtGui.QApplication.translate("FileSystemDock", "Folders First", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("FileSystemDock", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSystemEditor.setText(QtGui.QApplication.translate("FileSystemDock", "System Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenDefaultEditor.setText(QtGui.QApplication.translate("FileSystemDock", "Default Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRename.setText(QtGui.QApplication.translate("FileSystemDock", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRename.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRename.setShortcut(QtGui.QApplication.translate("FileSystemDock", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvertIntoProject.setText(QtGui.QApplication.translate("FileSystemDock", "Convert Into Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvertIntoProject.setToolTip(QtGui.QApplication.translate("FileSystemDock", "Convert current directory into project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetInTerminal.setText(QtGui.QApplication.translate("FileSystemDock", "Set In Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("FileSystemDock", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("FileSystemDock", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("FileSystemDock", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("FileSystemDock", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("FileSystemDock", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("FileSystemDock", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))

