# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/filterthroughcommand.ui'
#
# Created: Thu Mar 31 09:44:46 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FilterThroughCommand(object):
    def setupUi(self, FilterThroughCommand):
        FilterThroughCommand.setObjectName("FilterThroughCommand")
        FilterThroughCommand.resize(400, 325)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/actions/view-filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FilterThroughCommand.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(FilterThroughCommand)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setMargin(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(FilterThroughCommand)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboCommand = QtGui.QComboBox(FilterThroughCommand)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCommand.sizePolicy().hasHeightForWidth())
        self.comboCommand.setSizePolicy(sizePolicy)
        self.comboCommand.setEditable(True)
        self.comboCommand.setObjectName("comboCommand")
        self.horizontalLayout.addWidget(self.comboCommand)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(FilterThroughCommand)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioInputNone = QtGui.QRadioButton(self.groupBox)
        self.radioInputNone.setObjectName("radioInputNone")
        self.verticalLayout_2.addWidget(self.radioInputNone)
        self.radioInputSelection = QtGui.QRadioButton(self.groupBox)
        self.radioInputSelection.setChecked(True)
        self.radioInputSelection.setObjectName("radioInputSelection")
        self.verticalLayout_2.addWidget(self.radioInputSelection)
        self.radioInputDocument = QtGui.QRadioButton(self.groupBox)
        self.radioInputDocument.setObjectName("radioInputDocument")
        self.verticalLayout_2.addWidget(self.radioInputDocument)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(FilterThroughCommand)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioOutputDiscard = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputDiscard.setObjectName("radioOutputDiscard")
        self.verticalLayout.addWidget(self.radioOutputDiscard)
        self.radioOutputSelection = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputSelection.setChecked(True)
        self.radioOutputSelection.setObjectName("radioOutputSelection")
        self.verticalLayout.addWidget(self.radioOutputSelection)
        self.radioOutputDocument = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputDocument.setObjectName("radioOutputDocument")
        self.verticalLayout.addWidget(self.radioOutputDocument)
        self.radioOutputInsertText = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputInsertText.setObjectName("radioOutputInsertText")
        self.verticalLayout.addWidget(self.radioOutputInsertText)
        self.radioOutputInsertSnippet = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputInsertSnippet.setObjectName("radioOutputInsertSnippet")
        self.verticalLayout.addWidget(self.radioOutputInsertSnippet)
        self.radioOutputShowToolTip = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputShowToolTip.setObjectName("radioOutputShowToolTip")
        self.verticalLayout.addWidget(self.radioOutputShowToolTip)
        self.radioOutputShowAsHTML = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputShowAsHTML.setObjectName("radioOutputShowAsHTML")
        self.verticalLayout.addWidget(self.radioOutputShowAsHTML)
        self.radioOutputCreateNewDocument = QtGui.QRadioButton(self.groupBox_2)
        self.radioOutputCreateNewDocument.setObjectName("radioOutputCreateNewDocument")
        self.verticalLayout.addWidget(self.radioOutputCreateNewDocument)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtGui.QDialogButtonBox(FilterThroughCommand)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(FilterThroughCommand)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), FilterThroughCommand.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), FilterThroughCommand.reject)
        QtCore.QMetaObject.connectSlotsByName(FilterThroughCommand)

    def retranslateUi(self, FilterThroughCommand):
        FilterThroughCommand.setWindowTitle(QtGui.QApplication.translate("FilterThroughCommand", "Filter Through Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FilterThroughCommand", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.comboCommand.setProperty("className", QtGui.QApplication.translate("FilterThroughCommand", "bigPadding", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FilterThroughCommand", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.radioInputNone.setText(QtGui.QApplication.translate("FilterThroughCommand", "&None", None, QtGui.QApplication.UnicodeUTF8))
        self.radioInputSelection.setText(QtGui.QApplication.translate("FilterThroughCommand", "&Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.radioInputDocument.setText(QtGui.QApplication.translate("FilterThroughCommand", "&Document", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FilterThroughCommand", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputDiscard.setText(QtGui.QApplication.translate("FilterThroughCommand", "D&iscard", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputSelection.setText(QtGui.QApplication.translate("FilterThroughCommand", "Replace Se&lection", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputDocument.setText(QtGui.QApplication.translate("FilterThroughCommand", "Replace D&ocument", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputInsertText.setText(QtGui.QApplication.translate("FilterThroughCommand", "&Insert As Text", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputInsertSnippet.setText(QtGui.QApplication.translate("FilterThroughCommand", "Insert As Sni&ppet", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputShowToolTip.setText(QtGui.QApplication.translate("FilterThroughCommand", "Show As &ToolTip", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputShowAsHTML.setText(QtGui.QApplication.translate("FilterThroughCommand", "Show As &Html", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOutputCreateNewDocument.setText(QtGui.QApplication.translate("FilterThroughCommand", "Create &New Document", None, QtGui.QApplication.UnicodeUTF8))

import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FilterThroughCommand = QtGui.QDialog()
    ui = Ui_FilterThroughCommand()
    ui.setupUi(FilterThroughCommand)
    FilterThroughCommand.show()
    sys.exit(app.exec_())

