
# This file is automatically generated, do not edit.

cdef class Syntax:
    def __str__(self):
        return "<Syntax %s>" % self.name

cdef class ASIS(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxASIS
    name = "ASIS"

cdef class POSIX_BASIC(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxPosixBasic
    name = "POSIX_BASIC"

cdef class POSIX_EXTENDED(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxPosixExtended
    name = "POSIX_EXTENDED"

cdef class EMACS(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxEmacs
    name = "EMACS"

cdef class GREP(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxGrep
    name = "GREP"

cdef class GNU_REGEX(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxGnuRegex
    name = "GNU_REGEX"

cdef class JAVA(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxJava
    name = "JAVA"

cdef class PERL(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxPerl
    name = "PERL"

cdef class PERL_NG(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxPerl_NG
    name = "PERL_NG"

cdef class RUBY(Syntax):
    cdef OnigSyntaxType syntax = &OnigSyntaxRuby
    name = "RUBY"
