all: prymatex_64x64.png prymatex_32x32.png prymatex_24x24.png
	
	
prymatex_64x64.png: icon.svg
	inkscape -z -e $@ -w 64 -w 64 $^
	
prymatex_32x32.png: icon.svg
	inkscape -z -e $@ -w 32 -w 32 $^
	
prymatex_24x24.png: icon.svg
	inkscape -z -e $@ -w 24 -w 24 $^