all: prymatex_128x128.png prymatex_64x64.png prymatex_32x32.png prymatex_24x24.png
	
prymatex_128x128.png: icon2.svg
	inkscape -z -e $@ -w 128 -w 128 $^

prymatex_64x64.png: icon2.svg
	inkscape -z -e $@ -w 64 -w 64 $^
	
prymatex_32x32.png: icon2.svg
	inkscape -z -e $@ -w 32 -w 32 $^
	
prymatex_24x24.png: icon2.svg
	inkscape -z -e $@ -w 24 -w 24 $^