# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui/editorstatus.ui'
#
# Created: Wed Sep 28 20:06:53 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from prymatex.utils.i18n import ugettext as _
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CodeEditorStatus(object):
    def setupUi(self, CodeEditorStatus):
        CodeEditorStatus.setObjectName(_fromUtf8("CodeEditorStatus"))
        CodeEditorStatus.resize(468, 254)
        self.verticalLayout = QtGui.QVBoxLayout(CodeEditorStatus)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.status = QtGui.QWidget(CodeEditorStatus)
        self.status.setObjectName(_fromUtf8("status"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.status)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelLineColumn = QtGui.QLabel(self.status)
        self.labelLineColumn.setObjectName(_fromUtf8("labelLineColumn"))
        self.horizontalLayout_2.addWidget(self.labelLineColumn)
        self.syntaxMenu = QtGui.QComboBox(self.status)
        self.syntaxMenu.setObjectName(_fromUtf8("syntaxMenu"))
        self.horizontalLayout_2.addWidget(self.syntaxMenu)
        self.comboBox_2 = QtGui.QComboBox(self.status)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addWidget(self.status)
        self.goToLine = QtGui.QWidget(CodeEditorStatus)
        self.goToLine.setObjectName(_fromUtf8("goToLine"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.goToLine)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.buttonCloseGoToLine = QtGui.QPushButton(self.goToLine)
        self.buttonCloseGoToLine.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/dialog-close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCloseGoToLine.setIcon(icon)
        self.buttonCloseGoToLine.setFlat(True)
        self.buttonCloseGoToLine.setObjectName(_fromUtf8("buttonCloseGoToLine"))
        self.horizontalLayout_3.addWidget(self.buttonCloseGoToLine)
        self.labelGoToLine = QtGui.QLabel(self.goToLine)
        self.labelGoToLine.setObjectName(_fromUtf8("labelGoToLine"))
        self.horizontalLayout_3.addWidget(self.labelGoToLine)
        self.spinGoToLine = QtGui.QSpinBox(self.goToLine)
        self.spinGoToLine.setObjectName(_fromUtf8("spinGoToLine"))
        self.horizontalLayout_3.addWidget(self.spinGoToLine)
        spacerItem = QtGui.QSpacerItem(154, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonGoToLine = QtGui.QPushButton(self.goToLine)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/go-jump.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonGoToLine.setIcon(icon1)
        self.buttonGoToLine.setAutoDefault(True)
        self.buttonGoToLine.setDefault(True)
        self.buttonGoToLine.setObjectName(_fromUtf8("buttonGoToLine"))
        self.horizontalLayout_3.addWidget(self.buttonGoToLine)
        self.verticalLayout.addWidget(self.goToLine)
        self.findReplace = QtGui.QWidget(CodeEditorStatus)
        self.findReplace.setObjectName(_fromUtf8("findReplace"))
        self.gridLayout = QtGui.QGridLayout(self.findReplace)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonFindReplaceClose = QtGui.QPushButton(self.findReplace)
        self.pushButtonFindReplaceClose.setText(_fromUtf8(""))
        self.pushButtonFindReplaceClose.setIcon(icon)
        self.pushButtonFindReplaceClose.setFlat(True)
        self.pushButtonFindReplaceClose.setObjectName(_fromUtf8("pushButtonFindReplaceClose"))
        self.gridLayout.addWidget(self.pushButtonFindReplaceClose, 0, 0, 1, 1)
        self.labelFind = QtGui.QLabel(self.findReplace)
        self.labelFind.setObjectName(_fromUtf8("labelFind"))
        self.gridLayout.addWidget(self.labelFind, 0, 1, 1, 1)
        self.labelReplace = QtGui.QLabel(self.findReplace)
        self.labelReplace.setObjectName(_fromUtf8("labelReplace"))
        self.gridLayout.addWidget(self.labelReplace, 1, 1, 1, 1)
        self.lineEditFind = QtGui.QLineEdit(self.findReplace)
        self.lineEditFind.setObjectName(_fromUtf8("lineEditFind"))
        self.gridLayout.addWidget(self.lineEditFind, 0, 2, 1, 1)
        self.lineEditReplace = QtGui.QLineEdit(self.findReplace)
        self.lineEditReplace.setObjectName(_fromUtf8("lineEditReplace"))
        self.gridLayout.addWidget(self.lineEditReplace, 1, 2, 1, 1)
        self.pushFindPrevious = QtGui.QPushButton(self.findReplace)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/go-previous-view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushFindPrevious.setIcon(icon2)
        self.pushFindPrevious.setObjectName(_fromUtf8("pushFindPrevious"))
        self.gridLayout.addWidget(self.pushFindPrevious, 0, 3, 1, 1)
        self.pushFindNext = QtGui.QPushButton(self.findReplace)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/actions/go-next-view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushFindNext.setIcon(icon3)
        self.pushFindNext.setObjectName(_fromUtf8("pushFindNext"))
        self.gridLayout.addWidget(self.pushFindNext, 0, 4, 1, 1)
        self.pushReplacePrevious = QtGui.QPushButton(self.findReplace)
        self.pushReplacePrevious.setObjectName(_fromUtf8("pushReplacePrevious"))
        self.gridLayout.addWidget(self.pushReplacePrevious, 1, 3, 1, 1)
        self.pushReplaceNext = QtGui.QPushButton(self.findReplace)
        self.pushReplaceNext.setObjectName(_fromUtf8("pushReplaceNext"))
        self.gridLayout.addWidget(self.pushReplaceNext, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.findReplace)

        self.retranslateUi(CodeEditorStatus)
        QtCore.QMetaObject.connectSlotsByName(CodeEditorStatus)

    def retranslateUi(self, CodeEditorStatus):
        CodeEditorStatus.setWindowTitle(_('Form'))
        self.labelLineColumn.setText(_('TextLabel'))
        self.labelGoToLine.setText(_('Go to line:'))
        self.buttonGoToLine.setText(_('Go'))
        self.labelFind.setText(_('Find:'))
        self.labelReplace.setText(_('Replace:'))
        self.pushFindPrevious.setText(_('Previous'))
        self.pushFindNext.setToolTip(_('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Find Previous</p></body></html>'))
        self.pushFindNext.setText(_('Next'))
        self.pushReplacePrevious.setToolTip(_('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Nimbus Mono L\'; font-size:8pt; font-weight:600; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Replace &amp; Find Previous</p></body></html>'))
        self.pushReplacePrevious.setText(_('Replace'))
        self.pushReplaceNext.setText(_('Replace &All'))

from prymatex import resources_rc
