# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/fspane.ui'
#
# Created: Mon Jan  3 19:48:10 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FSPane(object):
    def setupUi(self, FSPane):
        FSPane.setObjectName("FSPane")
        FSPane.resize(265, 457)
        FSPane.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"\n"
"}")
        self.verticalLayout = QtGui.QVBoxLayout(FSPane)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonUp = QtGui.QPushButton(FSPane)
        self.buttonUp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/resources/actions/go-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUp.setIcon(icon)
        self.buttonUp.setIconSize(QtCore.QSize(16, 16))
        self.buttonUp.setFlat(True)
        self.buttonUp.setObjectName("buttonUp")
        self.horizontalLayout.addWidget(self.buttonUp)
        self.buttonBackRoot = QtGui.QPushButton(FSPane)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/resources/actions/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBackRoot.setIcon(icon1)
        self.buttonBackRoot.setIconSize(QtCore.QSize(16, 16))
        self.buttonBackRoot.setFlat(True)
        self.buttonBackRoot.setObjectName("buttonBackRoot")
        self.horizontalLayout.addWidget(self.buttonBackRoot)
        self.pushButton_2 = QtGui.QPushButton(FSPane)
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/resources/actions/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.buttonFilter = QtGui.QPushButton(FSPane)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/resources/actions/view-filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFilter.setIcon(icon3)
        self.buttonFilter.setIconSize(QtCore.QSize(16, 16))
        self.buttonFilter.setFlat(True)
        self.buttonFilter.setObjectName("buttonFilter")
        self.horizontalLayout.addWidget(self.buttonFilter)
        self.buttonSyncTabFile = QtGui.QPushButton(FSPane)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/resources/actions/system-switch-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSyncTabFile.setIcon(icon4)
        self.buttonSyncTabFile.setIconSize(QtCore.QSize(16, 16))
        self.buttonSyncTabFile.setFlat(True)
        self.buttonSyncTabFile.setObjectName("buttonSyncTabFile")
        self.horizontalLayout.addWidget(self.buttonSyncTabFile)
        self.buttonCollapseAll = QtGui.QPushButton(FSPane)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/resources/actions/debug-step-into.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCollapseAll.setIcon(icon5)
        self.buttonCollapseAll.setIconSize(QtCore.QSize(16, 16))
        self.buttonCollapseAll.setFlat(True)
        self.buttonCollapseAll.setObjectName("buttonCollapseAll")
        self.horizontalLayout.addWidget(self.buttonCollapseAll)
        self.pushShowHidden = QtGui.QPushButton(FSPane)
        self.pushShowHidden.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/actions/resources/actions/help-hint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushShowHidden.setIcon(icon6)
        self.pushShowHidden.setCheckable(True)
        self.pushShowHidden.setFlat(True)
        self.pushShowHidden.setObjectName("pushShowHidden")
        self.horizontalLayout.addWidget(self.pushShowHidden)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtGui.QComboBox(FSPane)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton = QtGui.QPushButton(FSPane)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resources/emblems/emblem-favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tree = FSTree(FSPane)
        self.tree.setObjectName("tree")
        self.verticalLayout.addWidget(self.tree)

        self.retranslateUi(FSPane)
        QtCore.QMetaObject.connectSlotsByName(FSPane)

    def retranslateUi(self, FSPane):
        FSPane.setWindowTitle(QtGui.QApplication.translate("FSPane", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUp.setToolTip(QtGui.QApplication.translate("FSPane", "Go up one level", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBackRoot.setToolTip(QtGui.QApplication.translate("FSPane", "Go previous place", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setToolTip(QtGui.QApplication.translate("FSPane", "Go next place", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFilter.setToolTip(QtGui.QApplication.translate("FSPane", "Filter settings", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSyncTabFile.setToolTip(QtGui.QApplication.translate("FSPane", "Sync folder with current editor file path", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCollapseAll.setToolTip(QtGui.QApplication.translate("FSPane", "Collapse Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushShowHidden.setToolTip(QtGui.QApplication.translate("FSPane", "Show Hidden Files", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setToolTip(QtGui.QApplication.translate("FSPane", "Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("FSPane", "Favourite places", None, QtGui.QApplication.UnicodeUTF8))

from fstree import FSTree
import res_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FSPane = QtGui.QWidget()
    ui = Ui_FSPane()
    ui.setupUi(FSPane)
    FSPane.show()
    sys.exit(app.exec_())

