# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/diego/Projects/prymatex/resources/ui/others/filterbundleitem.ui'
#
# Created: Wed Sep 17 09:55:02 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FilterThroughCommand(object):
    def setupUi(self, FilterThroughCommand):
        FilterThroughCommand.setObjectName("FilterThroughCommand")
        FilterThroughCommand.resize(400, 325)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/actions/view-filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FilterThroughCommand.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FilterThroughCommand)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FilterThroughCommand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboCommand = QtWidgets.QComboBox(FilterThroughCommand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCommand.sizePolicy().hasHeightForWidth())
        self.comboCommand.setSizePolicy(sizePolicy)
        self.comboCommand.setEditable(True)
        self.comboCommand.setObjectName("comboCommand")
        self.horizontalLayout.addWidget(self.comboCommand)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(FilterThroughCommand)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioInputNone = QtWidgets.QRadioButton(self.groupBox)
        self.radioInputNone.setObjectName("radioInputNone")
        self.verticalLayout_2.addWidget(self.radioInputNone)
        self.radioInputSelection = QtWidgets.QRadioButton(self.groupBox)
        self.radioInputSelection.setChecked(True)
        self.radioInputSelection.setObjectName("radioInputSelection")
        self.verticalLayout_2.addWidget(self.radioInputSelection)
        self.radioInputDocument = QtWidgets.QRadioButton(self.groupBox)
        self.radioInputDocument.setObjectName("radioInputDocument")
        self.verticalLayout_2.addWidget(self.radioInputDocument)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(FilterThroughCommand)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioOutputDiscard = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputDiscard.setObjectName("radioOutputDiscard")
        self.verticalLayout.addWidget(self.radioOutputDiscard)
        self.radioOutputSelection = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputSelection.setChecked(True)
        self.radioOutputSelection.setObjectName("radioOutputSelection")
        self.verticalLayout.addWidget(self.radioOutputSelection)
        self.radioOutputDocument = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputDocument.setObjectName("radioOutputDocument")
        self.verticalLayout.addWidget(self.radioOutputDocument)
        self.radioOutputInsertText = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputInsertText.setObjectName("radioOutputInsertText")
        self.verticalLayout.addWidget(self.radioOutputInsertText)
        self.radioOutputInsertSnippet = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputInsertSnippet.setObjectName("radioOutputInsertSnippet")
        self.verticalLayout.addWidget(self.radioOutputInsertSnippet)
        self.radioOutputShowToolTip = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputShowToolTip.setObjectName("radioOutputShowToolTip")
        self.verticalLayout.addWidget(self.radioOutputShowToolTip)
        self.radioOutputShowAsHTML = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputShowAsHTML.setObjectName("radioOutputShowAsHTML")
        self.verticalLayout.addWidget(self.radioOutputShowAsHTML)
        self.radioOutputCreateNewDocument = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioOutputCreateNewDocument.setObjectName("radioOutputCreateNewDocument")
        self.verticalLayout.addWidget(self.radioOutputCreateNewDocument)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(FilterThroughCommand)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(FilterThroughCommand)
        self.buttonBox.accepted.connect(FilterThroughCommand.accept)
        self.buttonBox.rejected.connect(FilterThroughCommand.reject)
        QtCore.QMetaObject.connectSlotsByName(FilterThroughCommand)

    def retranslateUi(self, FilterThroughCommand):
        _translate = QtCore.QCoreApplication.translate
        FilterThroughCommand.setWindowTitle(_translate("FilterThroughCommand", "Filter Through Command"))
        self.label.setText(_translate("FilterThroughCommand", "Command"))
        self.comboCommand.setProperty("className", _translate("FilterThroughCommand", "bigPadding"))
        self.groupBox.setTitle(_translate("FilterThroughCommand", "Input"))
        self.radioInputNone.setText(_translate("FilterThroughCommand", "&None"))
        self.radioInputSelection.setText(_translate("FilterThroughCommand", "&Selection"))
        self.radioInputDocument.setText(_translate("FilterThroughCommand", "&Document"))
        self.groupBox_2.setTitle(_translate("FilterThroughCommand", "Output"))
        self.radioOutputDiscard.setText(_translate("FilterThroughCommand", "D&iscard"))
        self.radioOutputSelection.setText(_translate("FilterThroughCommand", "Replace Se&lection"))
        self.radioOutputDocument.setText(_translate("FilterThroughCommand", "Replace D&ocument"))
        self.radioOutputInsertText.setText(_translate("FilterThroughCommand", "&Insert As Text"))
        self.radioOutputInsertSnippet.setText(_translate("FilterThroughCommand", "Insert As Sni&ppet"))
        self.radioOutputShowToolTip.setText(_translate("FilterThroughCommand", "Show As &ToolTip"))
        self.radioOutputShowAsHTML.setText(_translate("FilterThroughCommand", "Show As &Html"))
        self.radioOutputCreateNewDocument.setText(_translate("FilterThroughCommand", "Create &New Document"))

