#!/usr/bin/env python
# -*- coding: utf-8 -*-

INDENT_NONE = 0
INDENT_INCREASE = 1
INDENT_DECREASE = 2
INDENT_NEXTLINE = 3
INDENT_UNINDENT = 4
FOLDING_NONE = 0
FOLDING_START = 1
FOLDING_STOP = 2
FOLDING_INDENTED_START = 3
FOLDING_INDENTED_IGNORE = 4

